arm:
    hardware_interface:
        joint_offsets: # degrees
            joint_1: 0 
            joint_2: 0 
            joint_3: 0 
            joint_4: 0 
            joint_5: 0 
            joint_6: 0 
