
#include "class/voltageratioinput.gen.h"
#include "class/digitalinput.gen.h"
#include "class/digitaloutput.gen.h"
#include "class/rcservo.gen.h"
#include "class/voltageoutput.gen.h"
#include "class/accelerometer.gen.h"
#include "class/voltageinput.gen.h"
#include "class/capacitivetouch.gen.h"
#include "class/rfid.gen.h"
#include "class/gps.gen.h"
#include "class/gyroscope.gen.h"
#include "class/magnetometer.gen.h"
#include "class/spatial.gen.h"
#include "class/temperaturesensor.gen.h"
#include "class/encoder.gen.h"
#include "class/frequencycounter.gen.h"
#include "class/ir.gen.h"
#include "class/phsensor.gen.h"
#include "class/dcmotor.gen.h"
#include "class/currentinput.gen.h"
#include "class/stepper.gen.h"
#include "class/lcd.gen.h"
#include "class/dataadapter.gen.h"
#include "class/currentoutput.gen.h"
#include "class/motorpositioncontroller.gen.h"
#include "class/bldcmotor.gen.h"
#include "class/distancesensor.gen.h"
#include "class/humiditysensor.gen.h"
#include "class/lightsensor.gen.h"
#include "class/pressuresensor.gen.h"
#include "class/resistanceinput.gen.h"
#include "class/powerguard.gen.h"
#include "class/soundsensor.gen.h"
#include "class/hub.gen.h"
#include "class/generic.gen.h"
#include "class/meshdongle.gen.h"
#include "class/firmwareupgrade.gen.h"
#include "class/dictionary.gen.h"

const char *Phid_ClassName[PHIDGET_DEVICE_CLASS_COUNT] = {
	"PhidgetNone",
	"PhidgetAccelerometer",
	"PhidgetAdvancedServo",
	"PhidgetAnalog",
	"PhidgetBridge",
	"PhidgetEncoder",
	"PhidgetFrequencyCounter",
	"PhidgetGPS",
	"PhidgetHub",
	"PhidgetInterfaceKit",
	"PhidgetIR",
	"PhidgetLED",
	"PhidgetMeshDongle",
	"PhidgetMotorControl",
	"PhidgetPHSensor",
	"PhidgetRFID",
	"PhidgetServo",
	"PhidgetSpatial",
	"PhidgetStepper",
	"PhidgetTemperatureSensor",
	"PhidgetTextLCD",
	"PhidgetVINT",
	"PhidgetGeneric",
	"PhidgetFirmwareUpgrade",
	"PhidgetDictionary",
	"PhidgetDataAdapter",
};

const char *Phid_ChannelClassName[PHIDGET_CHANNEL_CLASS_COUNT] = {
	"PhidgetNone",
	"PhidgetAccelerometer",
	"PhidgetCurrentInput",
	"PhidgetDataAdapter",
	"PhidgetDCMotor",
	"PhidgetDigitalInput",
	"PhidgetDigitalOutput",
	"PhidgetDistanceSensor",
	"PhidgetEncoder",
	"PhidgetFrequencyCounter",
	"PhidgetGPS",
	"PhidgetLCD",
	"PhidgetGyroscope",
	"PhidgetHub",
	"PhidgetCapacitiveTouch",
	"PhidgetHumiditySensor",
	"PhidgetIR",
	"PhidgetLightSensor",
	"PhidgetMagnetometer",
	"PhidgetMeshDongle",
	"PhidgetPowerGuard",
	"PhidgetPressureSensor",
	"PhidgetRCServo",
	"PhidgetResistanceInput",
	"PhidgetRFID",
	"PhidgetSoundSensor",
	"PhidgetSpatial",
	"PhidgetStepper",
	"PhidgetTemperatureSensor",
	"PhidgetVoltageInput",
	"PhidgetVoltageOutput",
	"PhidgetVoltageRatioInput",
	"PhidgetFirmwareUpgrade",
	"PhidgetGeneric",
	"PhidgetMotorPositionController",
	"PhidgetBLDCMotor",
	"PhidgetDictionary",
	"PhidgetPHSensor",
	"PhidgetCurrentOutput",
};

const PhidgetUniqueDeviceDef Phidget_Unique_Device_Def[] = {
	{USB_PHIDGET(PHIDUID_IFKIT488, PHIDID_INTERFACEKIT_4_8_8, PHIDCLASS_INTERFACEKIT, USBVID_OLD,
	  USBID_0x8201, 0, 0, ifkit, 0, 4, 8, 8),
	  VERSION_RANGE(0, 101), "ifkit488", "PhidgetInterfaceKit 4/8/8",  {
		{PHIDCHUID_ifkit488_VOLTAGERATIOINPUT_000,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(4),	EXCLUSIVE(-1),	"Voltage Ratio Input"},
		{PHIDCHUID_ifkit488_DIGITALINPUT_000,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_ifkit488_DIGITALOUTPUT_000,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1000_OLD1, PHIDID_1000, PHIDCLASS_SERVO, USBVID_OLD, USBID_0x8101, 0, 0, servo,
	  1),
	  VERSION_RANGE(200, 201), "1000", "PhidgetServo 1-Motor",  {
		{PHIDCHUID_1000_RCSERVO_OLD1_200,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1000_OLD2, PHIDID_1000, PHIDCLASS_SERVO, USBVID_PHIDGETS, USBID_0x39, 0, 0,
	  servo, 1),
	  VERSION_RANGE(200, 201), "1000", "PhidgetServo 1-Motor",  {
		{PHIDCHUID_1000_RCSERVO_OLD2_200,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1000_NO_ECHO, PHIDID_1000, PHIDCLASS_SERVO, USBVID_PHIDGETS, USBID_0x39, 0, 0,
	  servo, 1),
	  VERSION_RANGE(300, 313), "1000", "PhidgetServo 1-Motor",  {
		{PHIDCHUID_1000_RCSERVO_300,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1000, PHIDID_1000, PHIDCLASS_SERVO, USBVID_PHIDGETS, USBID_0x39, 0, 0, servo,
	  1),
	  VERSION_RANGE(313, 400), "1000", "PhidgetServo 1-Motor",  {
		{PHIDCHUID_1000_RCSERVO_313,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1001_OLD1, PHIDID_1001, PHIDCLASS_SERVO, USBVID_OLD, USBID_0x8104, 0, 0, servo,
	  4),
	  VERSION_RANGE(200, 201), "1001", "PhidgetServo 4-Motor",  {
		{PHIDCHUID_1001_RCSERVO_OLD1_200,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(4),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1001_OLD2, PHIDID_1001, PHIDCLASS_SERVO, USBVID_PHIDGETS, USBID_0x38, 0, 0,
	  servo, 4),
	  VERSION_RANGE(200, 201), "1001", "PhidgetServo 4-Motor",  {
		{PHIDCHUID_1001_RCSERVO_OLD2_200,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(4),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1001_NO_ECHO, PHIDID_1001, PHIDCLASS_SERVO, USBVID_PHIDGETS, USBID_0x38, 0, 0,
	  servo, 4),
	  VERSION_RANGE(300, 313), "1001", "PhidgetServo 4-Motor",  {
		{PHIDCHUID_1001_RCSERVO_313,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(4),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1001, PHIDID_1001, PHIDCLASS_SERVO, USBVID_PHIDGETS, USBID_0x38, 0, 0, servo,
	  4),
	  VERSION_RANGE(313, 400), "1001", "PhidgetServo 4-Motor",  {
		{PHIDCHUID_1001_RCSERVO_400,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(4),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1002, PHIDID_1002, PHIDCLASS_ANALOG, USBVID_PHIDGETS, USBID_0x37, 0, 0, analog,
	  4),
	  VERSION_RANGE(100, 200), "1002", "PhidgetAnalog 4-Output",  {
		{PHIDCHUID_1002_VOLTAGEOUTPUT_100,	PHIDCHCLASS_VOLTAGEOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Voltage Output"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1008, PHIDID_1008, PHIDCLASS_ACCELEROMETER, USBVID_PHIDGETS, USBID_0x71, 0, 0,
	  accelerometer, 2),
	  VERSION_RANGE(0, 200), "1008", "PhidgetAccelerometer 2-Axis",  {
		{PHIDCHUID_1008_ACCELEROMETER_000,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"2-Axis Accelerometer"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1011, PHIDID_1011, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS, USBID_0x36, 0, 0,
	  ifkit, 2, 2, 2, 2),
	  VERSION_RANGE(0, 200), "1011", "PhidgetInterfaceKit 2/2/2",  {
		{PHIDCHUID_1011_VOLTAGEINPUT_000,	PHIDCHCLASS_VOLTAGEINPUT,
		 	PHIDCHSUBCLASS_VOLTAGEINPUT_SENSOR_PORT,	INDEX(0),	COUNT(2),	EXCLUSIVE(-1),	"Voltage Input"},
		{PHIDCHUID_1011_VOLTAGERATIOINPUT_000,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(2),	EXCLUSIVE(-1),	"Voltage Ratio Input"},
		{PHIDCHUID_1011_DIGITALINPUT_000,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(2),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_1011_DIGITALOUTPUT_000,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(2),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1012_NO_ECHO, PHIDID_1012, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS, USBID_0x44,
	  0, 1, ifkit, 0, 0, 16, 16),
	  VERSION_RANGE(0, 601), "1012", "PhidgetInterfaceKit 0/16/16",  {
		{PHIDCHUID_1012_DIGITALINPUT_000,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(16),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_1012_DIGITALOUTPUT_000,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(16),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1012_BITBUG, PHIDID_1012, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS, USBID_0x44,
	  0, 0, ifkit, 0, 0, 16, 16),
	  VERSION_RANGE(601, 602), "1012", "PhidgetInterfaceKit 0/16/16",  {
		{PHIDCHUID_1012_DIGITALINPUT_601,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(16),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_1012_DIGITALOUTPUT_601,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(16),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1012, PHIDID_1012, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS, USBID_0x44, 0, 0,
	  ifkit, 0, 0, 16, 16),
	  VERSION_RANGE(602, 700), "1012", "PhidgetInterfaceKit 0/16/16",  {
		{PHIDCHUID_1012_DIGITALINPUT_602,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(16),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_1012_DIGITALOUTPUT_602,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(16),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1013_NO_ECHO, PHIDID_1010_1013_1018_1019, PHIDCLASS_INTERFACEKIT,
	  USBVID_PHIDGETS, USBID_0x45, 0, 0, ifkit, 8, 8, 8, 8),
	  VERSION_RANGE(0, 821), "1013", "PhidgetInterfaceKit 8/8/8",  {
		{PHIDCHUID_1013_VOLTAGEINPUT_000,	PHIDCHCLASS_VOLTAGEINPUT,
		 	PHIDCHSUBCLASS_VOLTAGEINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Input"},
		{PHIDCHUID_1013_VOLTAGERATIOINPUT_000,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Ratio Input"},
		{PHIDCHUID_1013_DIGITALINPUT_000,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_1013_DIGITALOUTPUT_000,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1013, PHIDID_1010_1013_1018_1019, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS,
	  USBID_0x45, 0, 0, ifkit, 8, 8, 8, 8),
	  VERSION_RANGE(821, 900), "1013/1018/1019", "PhidgetInterfaceKit 8/8/8",  {
		{PHIDCHUID_1018_VOLTAGEINPUT_821,	PHIDCHCLASS_VOLTAGEINPUT,
		 	PHIDCHSUBCLASS_VOLTAGEINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Input"},
		{PHIDCHUID_1018_VOLTAGERATIOINPUT_821,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Ratio Input"},
		{PHIDCHUID_1018_DIGITALINPUT_821,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_1018_DIGITALOUTPUT_821,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1014_NO_ECHO, PHIDID_1014, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS, USBID_0x40,
	  0, 0, ifkit, 0, 0, 0, 4),
	  VERSION_RANGE(0, 704), "1014", "PhidgetInterfaceKit 0/0/4",  {
		{PHIDCHUID_1014_DIGITALOUTPUT_000,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Power Relay"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1014, PHIDID_1014, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS, USBID_0x40, 0, 0,
	  ifkit, 0, 0, 0, 4),
	  VERSION_RANGE(704, 800), "1014", "PhidgetInterfaceKit 0/0/4",  {
		{PHIDCHUID_1014_DIGITALOUTPUT_704,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Power Relay"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1015, PHIDID_1015, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS, USBID_0x76, 0, 0,
	  ifkit, 0, 0, 0, 0, 1),
	  VERSION_RANGE(0, 9999), "1015", "PhidgetLinearTouch",  {
		{PHIDCHUID_1015_CAPACITIVETOUCH_000,	PHIDCHCLASS_CAPACITIVETOUCH,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Capacitive Slider Sensor"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1016, PHIDID_1016, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS, USBID_0x77, 0, 0,
	  ifkit, 0, 0, 0, 0, 1),
	  VERSION_RANGE(0, 9999), "1016", "PhidgetCircularTouch",  {
		{PHIDCHUID_1016_CAPACITIVETOUCH_000,	PHIDCHCLASS_CAPACITIVETOUCH,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Capacitive Scroll Sensor"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1017, PHIDID_1017, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS, USBID_0x81, 0, 0,
	  ifkit, 0, 0, 0, 8),
	  VERSION_RANGE(0, 9999), "1017", "PhidgetInterfaceKit 0/0/8",  {
		{PHIDCHUID_1017_DIGITALOUTPUT_000,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Signal Relay"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1018, PHIDID_1010_1013_1018_1019, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS,
	  USBID_0x45, 0, 0, ifkit, 8, 8, 8, 8),
	  VERSION_RANGE(900, 1000), "1010/1018/1019", "PhidgetInterfaceKit 8/8/8",  {
		{PHIDCHUID_1018_VOLTAGEINPUT_900,	PHIDCHCLASS_VOLTAGEINPUT,
		 	PHIDCHSUBCLASS_VOLTAGEINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Input"},
		{PHIDCHUID_1018_VOLTAGERATIOINPUT_900,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Ratio Input"},
		{PHIDCHUID_1018_DIGITALINPUT_900,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_1018_DIGITALOUTPUT_900,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1018_3, PHIDID_1010_1013_1018_1019, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS,
	  USBID_0x45, 0, 0, ifkit, 8, 8, 8, 8),
	  VERSION_RANGE(1000, 1100), "1010/1018/1019", "PhidgetInterfaceKit 8/8/8",  {
		{PHIDCHUID_1018_VOLTAGEINPUT_1000,	PHIDCHCLASS_VOLTAGEINPUT,
		 	PHIDCHSUBCLASS_VOLTAGEINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Input"},
		{PHIDCHUID_1018_VOLTAGERATIOINPUT_1000,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Ratio Input"},
		{PHIDCHUID_1018_DIGITALINPUT_1000,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_1018_DIGITALOUTPUT_1000,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1023_OLD, PHIDID_1023, PHIDCLASS_RFID, USBVID_PHIDGETS, USBID_0x30, 0, 1, rfid,
	  0),
	  VERSION_RANGE(0, 104), "1023", "PhidgetRFID",  {
		{PHIDCHUID_1023_RFID_000,	PHIDCHCLASS_RFID,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"RFID Reader"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1023, PHIDID_1023, PHIDCLASS_RFID, USBVID_PHIDGETS, USBID_0x30, 0, 1, rfid, 0),
	 
	  VERSION_RANGE(104, 200), "1023", "PhidgetRFID",  {
		{PHIDCHUID_1023_RFID_104,	PHIDCHCLASS_RFID,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"RFID Reader"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1023_2OUTPUT_NO_ECHO, PHIDID_1023, PHIDCLASS_RFID, USBVID_PHIDGETS, USBID_0x31,
	  0, 1, rfid, 3),
	  VERSION_RANGE(200, 201), "1023", "PhidgetRFID",  {
		{PHIDCHUID_1023_RFID_200,	PHIDCHCLASS_RFID,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"RFID Reader"},
		{PHIDCHUID_1023_DIGITALOUTPUT_5V_200,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Digital Output"},
		{PHIDCHUID_1023_DIGITALOUTPUT_LED_200,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(1),
		 	COUNT(1),	EXCLUSIVE(-1),	"LED Driver"},
		{PHIDCHUID_1023_DIGITALOUTPUT_ONBOARD_LED_200,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,
		 	INDEX(2),	COUNT(1),	EXCLUSIVE(-1),	"Onboard LED"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1023_2OUTPUT, PHIDID_1023, PHIDCLASS_RFID, USBVID_PHIDGETS, USBID_0x31, 0, 0,
	  rfid, 3),
	  VERSION_RANGE(201, 300), "1023", "PhidgetRFID",  {
		{PHIDCHUID_1023_RFID_201,	PHIDCHCLASS_RFID,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"RFID Reader"},
		{PHIDCHUID_1023_DIGITALOUTPUT_5V_201,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Digital Output"},
		{PHIDCHUID_1023_DIGITALOUTPUT_LED_201,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(1),
		 	COUNT(1),	EXCLUSIVE(-1),	"LED Driver"},
		{PHIDCHUID_1023_DIGITALOUTPUT_ONBOARD_LED_201,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,
		 	INDEX(2),	COUNT(1),	EXCLUSIVE(-1),	"Onboard LED"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1024, PHIDID_1024, PHIDCLASS_RFID, USBVID_PHIDGETS, USBID_0x34, 0, 0, rfid, 3),
	 
	  VERSION_RANGE(100, 200), "1024", "PhidgetRFID Read-Write",  {
		{PHIDCHUID_1024_RFID_100,	PHIDCHCLASS_RFID,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"RFID Reader/Writer"},
		{PHIDCHUID_1024_DIGITALOUTPUT_5V_100,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Digital Output"},
		{PHIDCHUID_1024_DIGITALOUTPUT_LED_100,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(1),
		 	COUNT(1),	EXCLUSIVE(-1),	"LED Driver"},
		{PHIDCHUID_1024_DIGITALOUTPUT_ONBOARD_LED_100,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,
		 	INDEX(2),	COUNT(1),	EXCLUSIVE(-1),	"Onboard LED"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1030, PHIDID_1030, PHIDCLASS_LED, USBVID_PHIDGETS, USBID_0x4a, 0, 0, led, 64),
	  VERSION_RANGE(100, 300), "1030", "PhidgetLED-64",  {
		{PHIDCHUID_1030_DIGITALOUTPUT_100,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_LED_DRIVER,	INDEX(0),	COUNT(64),	EXCLUSIVE(-1),	"LED Driver"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1031, PHIDID_1031, PHIDCLASS_LED, USBVID_PHIDGETS, USBID_0x4c, 0, 0, led, 64),
	  VERSION_RANGE(100, 200), "1031", "PhidgetLED-64 Advanced",  {
		{PHIDCHUID_1031_DIGITALOUTPUT_100,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_LED_DRIVER,	INDEX(0),	COUNT(64),	EXCLUSIVE(-1),	"LED Driver"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1032, PHIDID_1032, PHIDCLASS_LED, USBVID_PHIDGETS, USBID_0x4c, 0, 0, led, 64),
	  VERSION_RANGE(200, 300), "1032", "PhidgetLED-64 Advanced",  {
		{PHIDCHUID_1032_DIGITALOUTPUT_200,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_LED_DRIVER,	INDEX(0),	COUNT(64),	EXCLUSIVE(-1),	"LED Driver"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1040, PHIDID_1040, PHIDCLASS_GPS, USBVID_PHIDGETS, USBID_0x79, 0, 0, gps, 1),
	  VERSION_RANGE(0, 9999), "1040", "PhidgetGPS",  {
		{PHIDCHUID_1040_GPS_000,	PHIDCHCLASS_GPS,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"GPS"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1041, PHIDID_1041, PHIDCLASS_SPATIAL, USBVID_PHIDGETS, USBID_0x7f, 0, 0,
	  spatial, 3, 0, 0),
	  VERSION_RANGE(200, 300), "1041", "PhidgetSpatial 0/0/3 Basic",  {
		{PHIDCHUID_1041_ACCELEROMETER_200,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Accelerometer"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1042, PHIDID_1042, PHIDCLASS_SPATIAL, USBVID_PHIDGETS, USBID_0x33, 0, 0,
	  spatial, 3, 3, 3, 1),
	  VERSION_RANGE(300, 400), "1042", "PhidgetSpatial 3/3/3 Basic",  {
		{PHIDCHUID_1042_ACCELEROMETER_300,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Accelerometer"},
		{PHIDCHUID_1042_GYROSCOPE_300,	PHIDCHCLASS_GYROSCOPE,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"3-Axis Gyroscope"},
		{PHIDCHUID_1042_MAGNETOMETER_300,	PHIDCHCLASS_MAGNETOMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Magnetometer"},
		{PHIDCHUID_1042_SPATIAL_300,	PHIDCHCLASS_SPATIAL,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Spatial"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1043, PHIDID_1043, PHIDCLASS_SPATIAL, USBVID_PHIDGETS, USBID_0x7f, 0, 0,
	  spatial, 3, 0, 0),
	  VERSION_RANGE(300, 400), "1043", "PhidgetSpatial Precision 0/0/3 High Resolution",  {
		{PHIDCHUID_1043_ACCELEROMETER_300,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Accelerometer"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1044, PHIDID_1044, PHIDCLASS_SPATIAL, USBVID_PHIDGETS, USBID_0x33, 0, 0,
	  spatial, 3, 3, 3, 1),
	  VERSION_RANGE(400, 500), "1044", "PhidgetSpatial Precision 3/3/3 High Resolution",  {
		{PHIDCHUID_1044_ACCELEROMETER_400,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Accelerometer"},
		{PHIDCHUID_1044_GYROSCOPE_400,	PHIDCHCLASS_GYROSCOPE,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"3-Axis Gyroscope"},
		{PHIDCHUID_1044_MAGNETOMETER_400,	PHIDCHCLASS_MAGNETOMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Magnetometer"},
		{PHIDCHUID_1044_SPATIAL_400,	PHIDCHCLASS_SPATIAL,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Spatial"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1044_1, PHIDID_1044, PHIDCLASS_SPATIAL, USBVID_PHIDGETS, USBID_0x33, 0, 1,
	  spatial, 3, 3, 3, 1),
	  VERSION_RANGE(500, 510), "1044", "PhidgetSpatial Precision 3/3/3 High Resolution",  {
		{PHIDCHUID_1044_ACCELEROMETER_500,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Accelerometer"},
		{PHIDCHUID_1044_GYROSCOPE_500,	PHIDCHCLASS_GYROSCOPE,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"3-Axis Gyroscope"},
		{PHIDCHUID_1044_MAGNETOMETER_500,	PHIDCHCLASS_MAGNETOMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Magnetometer"},
		{PHIDCHUID_1044_SPATIAL_500,	PHIDCHCLASS_SPATIAL,	PHIDCHSUBCLASS_SPATIAL_AHRS,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Spatial"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1044_1_510, PHIDID_1044, PHIDCLASS_SPATIAL, USBVID_PHIDGETS, USBID_0x33, 0, 0,
	  spatial, 3, 3, 3, 1),
	  VERSION_RANGE(510, 600), "1044", "PhidgetSpatial Precision 3/3/3 High Resolution",  {
		{PHIDCHUID_1044_ACCELEROMETER_510,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Accelerometer"},
		{PHIDCHUID_1044_GYROSCOPE_510,	PHIDCHCLASS_GYROSCOPE,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"3-Axis Gyroscope"},
		{PHIDCHUID_1044_MAGNETOMETER_510,	PHIDCHCLASS_MAGNETOMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Magnetometer"},
		{PHIDCHUID_1044_SPATIAL_510,	PHIDCHCLASS_SPATIAL,	PHIDCHSUBCLASS_SPATIAL_AHRS,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Spatial"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1045, PHIDID_1045, PHIDCLASS_TEMPERATURESENSOR, USBVID_PHIDGETS, USBID_0x3c, 0,
	  0, temperaturesensor, 2, 0),
	  VERSION_RANGE(100, 200), "1045", "PhidgetTemperatureSensor IR",  {
		{PHIDCHUID_1045_TEMPERATURESENSOR_IR_100,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor (IR)"},
		{PHIDCHUID_1045_TEMPERATURESENSOR_IC_100,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(1),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor (IC)"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1046_GAINBUG, PHIDID_1046, PHIDCLASS_BRIDGE, USBVID_PHIDGETS, USBID_0x3b, 0, 0,
	  bridge, 4),
	  VERSION_RANGE(100, 102), "1046", "PhidgetBridge 4-Input",  {
		{PHIDCHUID_1046_VOLTAGERATIOINPUT_100,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_BRIDGE,	INDEX(0),	COUNT(4),	EXCLUSIVE(-1),	"Bridge Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1046, PHIDID_1046, PHIDCLASS_BRIDGE, USBVID_PHIDGETS, USBID_0x3b, 0, 0, bridge,
	  4),
	  VERSION_RANGE(102, 200), "1046", "PhidgetBridge 4-Input",  {
		{PHIDCHUID_1046_VOLTAGERATIOINPUT_102,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_BRIDGE,	INDEX(0),	COUNT(4),	EXCLUSIVE(-1),	"Bridge Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1047, PHIDID_1047, PHIDCLASS_ENCODER, USBVID_PHIDGETS, USBID_0x4f, 0, 0,
	  encoder, 4, 4),
	  VERSION_RANGE(100, 200), "1047", "PhidgetEncoder HighSpeed 4-Input",  {
		{PHIDCHUID_1047_ENCODER_100,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(4),
		 	EXCLUSIVE(-1),	"Encoder Input"},
		{PHIDCHUID_1047_DIGITALINPUT_100,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Digital Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1047_2, PHIDID_1047, PHIDCLASS_ENCODER, USBVID_PHIDGETS, USBID_0x4f, 0, 0,
	  encoder, 4, 4),
	  VERSION_RANGE(200, 300), "1047", "PhidgetEncoder HighSpeed 4-Input",  {
		{PHIDCHUID_1047_ENCODER_200,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(4),
		 	EXCLUSIVE(-1),	"Encoder Input"},
		{PHIDCHUID_1047_DIGITALINPUT_200,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Digital Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1048, PHIDID_1048, PHIDCLASS_TEMPERATURESENSOR, USBVID_PHIDGETS, USBID_0x32, 0,
	  0, temperaturesensor, 5, 4),
	  VERSION_RANGE(100, 200), "1048", "PhidgetTemperatureSensor 4-Input",  {
		{PHIDCHUID_1048_TEMPERATURESENSOR_THERMOCOUPLE_100,	PHIDCHCLASS_TEMPERATURESENSOR,
		 	PHIDCHSUBCLASS_TEMPERATURESENSOR_THERMOCOUPLE,	INDEX(0),	COUNT(4),	EXCLUSIVE(-1),	"Thermocouple Input"},
		{PHIDCHUID_1048_TEMPERATURESENSOR_IC_100,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(4),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor (IC)"},
		{PHIDCHUID_1048_VOLTAGEINPUT_100,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1048_1_2, PHIDID_1048, PHIDCLASS_TEMPERATURESENSOR, USBVID_PHIDGETS, USBID_0x32,
	  0, 0, temperaturesensor, 5, 4),
	  VERSION_RANGE(200, 300), "1048", "PhidgetTemperatureSensor 4-Input",  {
		{PHIDCHUID_1048_TEMPERATURESENSOR_THERMOCOUPLE_200,	PHIDCHCLASS_TEMPERATURESENSOR,
		 	PHIDCHSUBCLASS_TEMPERATURESENSOR_THERMOCOUPLE,	INDEX(0),	COUNT(4),	EXCLUSIVE(-1),	"Thermocouple Input"},
		{PHIDCHUID_1048_TEMPERATURESENSOR_IC_200,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(4),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor (IC)"},
		{PHIDCHUID_1048_VOLTAGEINPUT_200,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1049, PHIDID_1049, PHIDCLASS_SPATIAL, USBVID_PHIDGETS, USBID_0x7f, 0, 0,
	  spatial, 3, 0, 0),
	  VERSION_RANGE(0, 200), "1049", "PhidgetSpatial 0/0/3",  {
		{PHIDCHUID_1049_ACCELEROMETER_000,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Accelerometer"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1051_OLD, PHIDID_1051, PHIDCLASS_TEMPERATURESENSOR, USBVID_PHIDGETS, USBID_0x70,
	  0, 0, temperaturesensor, 2, 0),
	  VERSION_RANGE(0, 200), "1051", "PhidgetTemperatureSensor 1-Input",  {
		{PHIDCHUID_1051_TEMPERATURESENSOR_THERMOCOUPLE_000,	PHIDCHCLASS_TEMPERATURESENSOR,
		 	PHIDCHSUBCLASS_TEMPERATURESENSOR_THERMOCOUPLE,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Thermocouple Input"},
		{PHIDCHUID_1051_TEMPERATURESENSOR_IC_000,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(1),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor (IC)"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1051, PHIDID_1051, PHIDCLASS_TEMPERATURESENSOR, USBVID_PHIDGETS, USBID_0x70, 0,
	  0, temperaturesensor, 2, 1),
	  VERSION_RANGE(200, 300), "1051", "PhidgetTemperatureSensor 1-Input",  {
		{PHIDCHUID_1051_TEMPERATURESENSOR_THERMOCOUPLE_200,	PHIDCHCLASS_TEMPERATURESENSOR,
		 	PHIDCHSUBCLASS_TEMPERATURESENSOR_THERMOCOUPLE,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Thermocouple Input"},
		{PHIDCHUID_1051_TEMPERATURESENSOR_IC_200,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(1),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor (IC)"},
		{PHIDCHUID_1051_VOLTAGEINPUT_200,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1051_AD22100, PHIDID_1051, PHIDCLASS_TEMPERATURESENSOR, USBVID_PHIDGETS,
	  USBID_0x70, 0, 0, temperaturesensor, 2, 1),
	  VERSION_RANGE(300, 400), "1051", "PhidgetTemperatureSensor 1-Input",  {
		{PHIDCHUID_1051_TEMPERATURESENSOR_THERMOCOUPLE_300,	PHIDCHCLASS_TEMPERATURESENSOR,
		 	PHIDCHSUBCLASS_TEMPERATURESENSOR_THERMOCOUPLE,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Thermocouple Input"},
		{PHIDCHUID_1051_TEMPERATURESENSOR_IC_300,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(1),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor (IC)"},
		{PHIDCHUID_1051_VOLTAGEINPUT_300,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1051_TERMINAL_BLOCKS, PHIDID_1051, PHIDCLASS_TEMPERATURESENSOR, USBVID_PHIDGETS,
	  USBID_0x70, 0, 0, temperaturesensor, 2, 1),
	  VERSION_RANGE(400, 500), "1051", "PhidgetTemperatureSensor 1-Input",  {
		{PHIDCHUID_1051_TEMPERATURESENSOR_THERMOCOUPLE_400,	PHIDCHCLASS_TEMPERATURESENSOR,
		 	PHIDCHSUBCLASS_TEMPERATURESENSOR_THERMOCOUPLE,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Thermocouple Input"},
		{PHIDCHUID_1051_TEMPERATURESENSOR_IC_400,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(1),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor (IC)"},
		{PHIDCHUID_1051_VOLTAGEINPUT_400,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1052_OLD, PHIDID_1052, PHIDCLASS_ENCODER, USBVID_PHIDGETS, USBID_0x4b, 0, 1,
	  encoder, 1, 1),
	  VERSION_RANGE(0, 101), "1052", "PhidgetEncoder",  {
		{PHIDCHUID_1052_ENCODER_000,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Encoder Input"},
		{PHIDCHUID_1052_DIGITALINPUT_000,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Digital Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1052_v1, PHIDID_1052, PHIDCLASS_ENCODER, USBVID_PHIDGETS, USBID_0x4b, 0, 1,
	  encoder, 1, 1),
	  VERSION_RANGE(101, 110), "1052", "PhidgetEncoder",  {
		{PHIDCHUID_1052_ENCODER_101,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Encoder Input"},
		{PHIDCHUID_1052_DIGITALINPUT_101,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Digital Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1052_v2, PHIDID_1052, PHIDCLASS_ENCODER, USBVID_PHIDGETS, USBID_0x4b, 0, 1,
	  encoder, 1, 1),
	  VERSION_RANGE(110, 300), "1052", "PhidgetEncoder",  {
		{PHIDCHUID_1052_ENCODER_110,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Encoder Input"},
		{PHIDCHUID_1052_DIGITALINPUT_110,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Digital Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1053, PHIDID_1053, PHIDCLASS_ACCELEROMETER, USBVID_PHIDGETS, USBID_0x71, 0, 0,
	  accelerometer, 2),
	  VERSION_RANGE(300, 400), "1053", "PhidgetAccelerometer 2-Axis",  {
		{PHIDCHUID_1053_ACCELEROMETER_300,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"2-Axis Accelerometer"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1054, PHIDID_1054, PHIDCLASS_FREQUENCYCOUNTER, USBVID_PHIDGETS, USBID_0x35, 0,
	  0, frequencycounter, 2),
	  VERSION_RANGE(0, 200), "1054", "PhidgetFrequencyCounter",  {
		{PHIDCHUID_1054_FREQUENCYCOUNTER_000,	PHIDCHCLASS_FREQUENCYCOUNTER,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(2),	EXCLUSIVE(-1),	"Frequency Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1055, PHIDID_1055, PHIDCLASS_IR, USBVID_PHIDGETS, USBID_0x4d, 0, 0, ir, 1),
	  VERSION_RANGE(100, 200), "1055", "PhidgetIR",  {
		{PHIDCHUID_1055_IR_100,	PHIDCHCLASS_IR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),
		 	"IR Receiver Transmitter"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1055_1_USB, PHIDID_1055, PHIDCLASS_IR, USBVID_PHIDGETS, USBID_0x4d, 0, 0, ir,
	  1),
	  VERSION_RANGE(200, 300), "1055", "PhidgetIR",  {
		{PHIDCHUID_1055_IR_200_USB,	PHIDCHCLASS_IR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"IR Receiver Transmitter"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_1055_1_VINT, PHIDID_1055, VINTID_0x4d), VERSION_RANGE(200, 300), "1055",
	  "PhidgetIR",  {
		{PHIDCHUID_1055_IR_200_VINT,	PHIDCHCLASS_IR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"IR Receiver Transmitter"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1056, PHIDID_1056, PHIDCLASS_SPATIAL, USBVID_PHIDGETS, USBID_0x33, 0, 0,
	  spatial, 3, 3, 3, 1),
	  VERSION_RANGE(0, 200), "1056", "PhidgetSpatial 3/3/3",  {
		{PHIDCHUID_1056_ACCELEROMETER_000,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Accelerometer"},
		{PHIDCHUID_1056_GYROSCOPE_000,	PHIDCHCLASS_GYROSCOPE,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"3-Axis Gyroscope"},
		{PHIDCHUID_1056_MAGNETOMETER_000,	PHIDCHCLASS_MAGNETOMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Magnetometer"},
		{PHIDCHUID_1056_SPATIAL_000,	PHIDCHCLASS_SPATIAL,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Spatial"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1056_NEG_GAIN, PHIDID_1056, PHIDCLASS_SPATIAL, USBVID_PHIDGETS, USBID_0x33, 0,
	  0, spatial, 3, 3, 3, 1),
	  VERSION_RANGE(200, 300), "1056", "PhidgetSpatial 3/3/3",  {
		{PHIDCHUID_1056_ACCELEROMETER_200,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Accelerometer"},
		{PHIDCHUID_1056_GYROSCOPE_200,	PHIDCHCLASS_GYROSCOPE,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"3-Axis Gyroscope"},
		{PHIDCHUID_1056_MAGNETOMETER_200,	PHIDCHCLASS_MAGNETOMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Magnetometer"},
		{PHIDCHUID_1056_SPATIAL_200,	PHIDCHCLASS_SPATIAL,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Spatial"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1057, PHIDID_1057, PHIDCLASS_ENCODER, USBVID_PHIDGETS, USBID_0x80, 0, 1,
	  encoder, 1),
	  VERSION_RANGE(300, 400), "1057", "PhidgetEncoder HighSpeed",  {
		{PHIDCHUID_1057_ENCODER_300,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Encoder Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1057_3, PHIDID_1057, PHIDCLASS_ENCODER, USBVID_PHIDGETS, USBID_0x80, 0, 0,
	  encoder, 1),
	  VERSION_RANGE(400, 500), "1057", "PhidgetEncoder HighSpeed",  {
		{PHIDCHUID_1057_ENCODER_400,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Encoder Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1058, PHIDID_1058, PHIDCLASS_PHSENSOR, USBVID_PHIDGETS, USBID_0x74, 0, 0,
	  phsensor, 1, 1),
	  VERSION_RANGE(100, 200), "1058", "PhidgetPHSensor",  {
		{PHIDCHUID_1058_VOLTAGEINPUT_100,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{PHIDCHUID_1058_PHADAPTER_100,	PHIDCHCLASS_PHSENSOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"PH Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1059, PHIDID_1059, PHIDCLASS_ACCELEROMETER, USBVID_PHIDGETS, USBID_0x7e, 0, 0,
	  accelerometer, 3),
	  VERSION_RANGE(400, 500), "1059", "PhidgetAccelerometer 3-Axis",  {
		{PHIDCHUID_1059_ACCELEROMETER_400,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Accelerometer"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1060, PHIDID_1060, PHIDCLASS_MOTORCONTROL, USBVID_PHIDGETS, USBID_0x58, 0, 0,
	  motorcontrol, 2, 4, 0, 0, 0, 0),
	  VERSION_RANGE(100, 200), "1060", "PhidgetMotorControl LV",  {
		{PHIDCHUID_1060_DCMOTOR_100,	PHIDCHCLASS_DCMOTOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(2),
		 	EXCLUSIVE(-1),	"DC Motor Controller"},
		{PHIDCHUID_1060_DIGITALINPUT_100,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Digital Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1061, PHIDID_1061, PHIDCLASS_ADVANCEDSERVO, USBVID_PHIDGETS, USBID_0x3a, 0, 0,
	  advancedservo, 8, 8),
	  VERSION_RANGE(100, 200), "1061", "PhidgetAdvancedServo 8-Motor",  {
		{PHIDCHUID_1061_RCSERVO_100,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(8),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{PHIDCHUID_1061_CURRENTINPUT_100,	PHIDCHCLASS_CURRENTINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"RC Servo Motor Current Sensor"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1061_PGOOD_FLAG, PHIDID_1061, PHIDCLASS_ADVANCEDSERVO, USBVID_PHIDGETS,
	  USBID_0x3a, 0, 0, advancedservo, 8, 8),
	  VERSION_RANGE(200, 300), "1061", "PhidgetAdvancedServo 8-Motor",  {
		{PHIDCHUID_1061_RCSERVO_200,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(8),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{PHIDCHUID_1061_CURRENTINPUT_200,	PHIDCHCLASS_CURRENTINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"RC Servo Motor Current Sensor"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1061_CURSENSE_FIX, PHIDID_1061, PHIDCLASS_ADVANCEDSERVO, USBVID_PHIDGETS,
	  USBID_0x3a, 0, 0, advancedservo, 8, 8),
	  VERSION_RANGE(300, 400), "1061", "PhidgetAdvancedServo 8-Motor",  {
		{PHIDCHUID_1061_RCSERVO_300,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(8),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{PHIDCHUID_1061_CURRENTINPUT_300,	PHIDCHCLASS_CURRENTINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"RC Servo Motor Current Sensor"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_RCC0004, PHIDID_RCC0004, PHIDCLASS_ADVANCEDSERVO, USBVID_PHIDGETS, USBID_0x3a,
	  0, 0, advancedservo, 8, 0),
	  VERSION_RANGE(400, 500), "RCC0004", "PhidgetAdvancedServo 8-Motor",  {
		{PHIDCHUID_RCC0004_RCSERVO_400,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(8),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1062, PHIDID_1062, PHIDCLASS_STEPPER, USBVID_PHIDGETS, USBID_0x7a, 0, 0,
	  stepper, 4),
	  VERSION_RANGE(100, 200), "1062", "PhidgetStepper Unipolar 4-Motor",  {
		{PHIDCHUID_1062_STEPPER_100,	PHIDCHCLASS_STEPPER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(4),
		 	EXCLUSIVE(-1),	"Unipolar Stepper Controller"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1063, PHIDID_1063, PHIDCLASS_STEPPER, USBVID_PHIDGETS, USBID_0x7b, 0, 0,
	  stepper, 1, 4, 1),
	  VERSION_RANGE(100, 200), "1063", "PhidgetStepper Bipolar 1-Motor",  {
		{PHIDCHUID_1063_STEPPER_100,	PHIDCHCLASS_STEPPER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Bipolar Stepper Controller"},
		{PHIDCHUID_1063_DIGITALINPUT_100,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_1063_CURRENTINPUT_100,	PHIDCHCLASS_CURRENTINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Bipolar Stepper Current Sensor"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1064, PHIDID_1064, PHIDCLASS_MOTORCONTROL, USBVID_PHIDGETS, USBID_0x59, 0, 0,
	  motorcontrol, 2, 0, 0, 0, 0, 2),
	  VERSION_RANGE(100, 200), "1064", "PhidgetMotorControl HC",  {
		{PHIDCHUID_1064_DCMOTOR_100,	PHIDCHCLASS_DCMOTOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(2),
		 	EXCLUSIVE(-1),	"DC Motor Controller"},
		{PHIDCHUID_1064_CURRENTINPUT_100,	PHIDCHCLASS_CURRENTINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(2),	EXCLUSIVE(-1),	"DC Motor Current Sensor"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1065, PHIDID_1065, PHIDCLASS_MOTORCONTROL, USBVID_PHIDGETS, USBID_0x3e, 0, 0,
	  motorcontrol, 1, 2, 1, 3, 2, 1),
	  VERSION_RANGE(100, 200), "1065", "PhidgetMotorControl 1-Motor",  {
		{PHIDCHUID_1065_DCMOTOR_100,	PHIDCHCLASS_DCMOTOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"DC Motor Controller"},
		{PHIDCHUID_1065_DIGITALINPUT_100,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(2),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_1065_ENCODER_100,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Encoder Input"},
		{PHIDCHUID_1065_VOLTAGEINPUT_100,	PHIDCHCLASS_VOLTAGEINPUT,
		 	PHIDCHSUBCLASS_VOLTAGEINPUT_SENSOR_PORT,	INDEX(0),	COUNT(2),	EXCLUSIVE(-1),	"Voltage Input"},
		{PHIDCHUID_1065_VOLTAGEINPUT_SUPPLY_100,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,
		 	INDEX(2),	COUNT(1),	EXCLUSIVE(-1),	"Supply Voltage Sensor"},
		{PHIDCHUID_1065_VOLTAGERATIOINPUT_100,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(2),	EXCLUSIVE(-1),	"Voltage Ratio Input"},
		{PHIDCHUID_1065_CURRENTINPUT_100,	PHIDCHCLASS_CURRENTINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"DC Motor Current Sensor"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1066, PHIDID_1066, PHIDCLASS_ADVANCEDSERVO, USBVID_PHIDGETS, USBID_0x82, 0, 0,
	  advancedservo, 1, 1),
	  VERSION_RANGE(100, 200), "1066", "PhidgetAdvancedServo 1-Motor",  {
		{PHIDCHUID_1066_RCSERVO_100,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{PHIDCHUID_1066_CURRENTINPUT_100,	PHIDCHCLASS_CURRENTINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"RC Servo Motor Current Sensor"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1067, PHIDID_1067, PHIDCLASS_STEPPER, USBVID_PHIDGETS, USBID_0x7b, 0, 0,
	  stepper, 1),
	  VERSION_RANGE(200, 300), "1067", "PhidgetStepper Bipolar HC",  {
		{PHIDCHUID_1067_STEPPER_200,	PHIDCHCLASS_STEPPER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Bipolar Stepper Controller"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1067_1, PHIDID_1067, PHIDCLASS_STEPPER, USBVID_PHIDGETS, USBID_0x7b, 0, 0,
	  stepper, 1),
	  VERSION_RANGE(300, 400), "1067", "PhidgetStepper Bipolar HC",  {
		{PHIDCHUID_1067_STEPPER_300,	PHIDCHCLASS_STEPPER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Bipolar Stepper Controller"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1202_IFKIT_NO_ECHO, PHIDID_1202_1203, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS,
	  USBID_0x7d, 0, 0, ifkit, 8, 8, 8, 8),
	  VERSION_RANGE(0, 120), "1202/1203", "PhidgetInterfaceKit 8/8/8",  {
		{PHIDCHUID_1202_VOLTAGEINPUT_000,	PHIDCHCLASS_VOLTAGEINPUT,
		 	PHIDCHSUBCLASS_VOLTAGEINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Input"},
		{PHIDCHUID_1202_VOLTAGERATIOINPUT_000,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Ratio Input"},
		{PHIDCHUID_1202_DIGITALINPUT_000,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_1202_DIGITALOUTPUT_000,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1202_IFKIT, PHIDID_1202_1203, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS,
	  USBID_0x7d, 0, 0, ifkit, 8, 8, 8, 8),
	  VERSION_RANGE(120, 200), "1202/1203", "PhidgetInterfaceKit 8/8/8",  {
		{PHIDCHUID_1202_VOLTAGEINPUT_120,	PHIDCHCLASS_VOLTAGEINPUT,
		 	PHIDCHSUBCLASS_VOLTAGEINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Input"},
		{PHIDCHUID_1202_VOLTAGERATIOINPUT_120,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Ratio Input"},
		{PHIDCHUID_1202_DIGITALINPUT_120,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_1202_DIGITALOUTPUT_120,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1202_TEXTLCD, PHIDID_1202_1203, PHIDCLASS_TEXTLCD, USBVID_PHIDGETS, USBID_0x7d,
	  1, 0, textlcd, 1),
	  VERSION_RANGE(0, 200), "1202/1203", "PhidgetTextLCD 20X2",  {
		{PHIDCHUID_1202_TEXTLCD_000,	PHIDCHCLASS_LCD,	PHIDCHSUBCLASS_LCD_TEXT,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Text LCD"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1202_IFKIT_FAST, PHIDID_1202_1203, PHIDCLASS_INTERFACEKIT, USBVID_PHIDGETS,
	  USBID_0x7d, 0, 0, ifkit, 8, 8, 8, 8),
	  VERSION_RANGE(200, 300), "1202/1203", "PhidgetInterfaceKit 8/8/8",  {
		{PHIDCHUID_1202_VOLTAGEINPUT_300,	PHIDCHCLASS_VOLTAGEINPUT,
		 	PHIDCHSUBCLASS_VOLTAGEINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Input"},
		{PHIDCHUID_1202_VOLTAGERATIOINPUT_300,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Ratio Input"},
		{PHIDCHUID_1202_DIGITALINPUT_300,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_1202_DIGITALOUTPUT_300,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1202_TEXTLCD_BRIGHTNESS, PHIDID_1202_1203, PHIDCLASS_TEXTLCD, USBVID_PHIDGETS,
	  USBID_0x7d, 1, 0, textlcd, 1),
	  VERSION_RANGE(200, 9999), "1202/1203", "PhidgetTextLCD 20X2",  {
		{PHIDCHUID_1202_TEXTLCD_200,	PHIDCHCLASS_LCD,	PHIDCHSUBCLASS_LCD_TEXT,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Text LCD"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1204, PHIDID_1204, PHIDCLASS_TEXTLCD, USBVID_PHIDGETS, USBID_0x3d, 0, 0,
	  textlcd, 2),
	  VERSION_RANGE(0, 9999), "1204", "PhidgetTextLCD Adapter",  {
		{PHIDCHUID_1204_TEXTLCD_000,	PHIDCHCLASS_LCD,	PHIDCHSUBCLASS_LCD_TEXT,	INDEX(0),	COUNT(2),
		 	EXCLUSIVE(-1),	"Text LCD"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1215, PHIDID_1215__1218, PHIDCLASS_TEXTLCD, USBVID_PHIDGETS, USBID_0x52, 0, 0,
	  textlcd, 1),
	  VERSION_RANGE(0, 9999), "1215/1216/1217/1218", "PhidgetTextLCD 20X2",  {
		{PHIDCHUID_1215_TEXTLCD_000,	PHIDCHCLASS_LCD,	PHIDCHSUBCLASS_LCD_TEXT,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Text LCD"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_1219, PHIDID_1219__1222, PHIDCLASS_TEXTLCD, USBVID_PHIDGETS, USBID_0x53, 0, 1,
	  textlcd, 1, 8, 8),
	  VERSION_RANGE(0, 9999), "1219/1220/1221/1222", "PhidgetTextLCD 20X2 with InterfaceKit 0/8/8",  {
		{PHIDCHUID_1219_TEXTLCD_000,	PHIDCHCLASS_LCD,	PHIDCHSUBCLASS_LCD_TEXT,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Text LCD"},
		{PHIDCHUID_1219_DIGITALINPUT_000,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_1219_DIGITALOUTPUT_000,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(8),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DIGITALINPUT_PORT, PHIDID_DIGITALINPUT_PORT, VINTID_0x1), VERSION_RANGE(100,
	  200), "DIGITALINPUT_PORT", "Hub Port - Digital Input Mode",  {
		{PHIDCHUID_HUB_DIGITALINPUT_100,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Digital Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DIGITALOUTPUT_PORT, PHIDID_DIGITALOUTPUT_PORT, VINTID_0x2), VERSION_RANGE(100,
	  110), "DIGITALOUTPUT_PORT", "Hub Port - Digital Output Mode",  {
		{PHIDCHUID_HUB_DIGITALOUTPUT_100,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_DUTY_CYCLE,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DIGITALOUTPUT_PORT_FAILSAFE, PHIDID_DIGITALOUTPUT_PORT, VINTID_0x2),
	  VERSION_RANGE(110, 200), "DIGITALOUTPUT_PORT", "Hub Port - Digital Output Mode",  {
		{PHIDCHUID_HUB_DIGITALOUTPUT_110,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_DUTY_CYCLE,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_VOLTAGEINPUT_PORT, PHIDID_VOLTAGEINPUT_PORT, VINTID_0x3), VERSION_RANGE(100,
	  110), "VOLTAGEINPUT_PORT", "Hub Port - Voltage Input Mode",  {
		{PHIDCHUID_HUB_VOLTAGEINPUT_100,	PHIDCHCLASS_VOLTAGEINPUT,
		 	PHIDCHSUBCLASS_VOLTAGEINPUT_SENSOR_PORT,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_VOLTAGEINPUT_PORT_5V25, PHIDID_VOLTAGEINPUT_PORT, VINTID_0x3),
	  VERSION_RANGE(110, 200), "VOLTAGEINPUT_PORT", "Hub Port - Voltage Input Mode",  {
		{PHIDCHUID_HUB_VOLTAGEINPUT_110,	PHIDCHCLASS_VOLTAGEINPUT,
		 	PHIDCHSUBCLASS_VOLTAGEINPUT_SENSOR_PORT,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_VOLTAGERATIOINPUT_PORT, PHIDID_VOLTAGERATIOINPUT_PORT, VINTID_0x4),
	  VERSION_RANGE(100, 200), "VOLTAGERATIOINPUT_PORT", "Hub Port - Voltage Ratio Mode",  {
		{PHIDCHUID_HUB_VOLTAGERATIOINPUT_100,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Voltage Ratio Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_ADP1000, PHIDID_ADP1000, VINTID_0x1d), VERSION_RANGE(100, 200), "ADP1000",
	  "pH Adapter Phidget",  {
		{PHIDCHUID_ADP1000_PHSENSOR_100,	PHIDCHCLASS_PHSENSOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"PH Sensor Input"},
		{PHIDCHUID_ADP1000_VOLTAGEINPUT_100,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DAQ1000, PHIDID_DAQ1000, VINTID_0x32), VERSION_RANGE(100, 110), "DAQ1000",
	  "8x Voltage Input Phidget",  {
		{PHIDCHUID_DAQ1000_VOLTAGERATIOINPUT_100,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Ratio Input"},
		{PHIDCHUID_DAQ1000_VOLTAGEINPUT_100,	PHIDCHCLASS_VOLTAGEINPUT,
		 	PHIDCHSUBCLASS_VOLTAGEINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DAQ1000_5V25, PHIDID_DAQ1000, VINTID_0x32), VERSION_RANGE(110, 200), "DAQ1000",
	  "8x Voltage Input Phidget",  {
		{PHIDCHUID_DAQ1000_VOLTAGERATIOINPUT_110,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Ratio Input"},
		{PHIDCHUID_DAQ1000_VOLTAGEINPUT_110,	PHIDCHCLASS_VOLTAGEINPUT,
		 	PHIDCHSUBCLASS_VOLTAGEINPUT_SENSOR_PORT,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_OUT1000, PHIDID_OUT1000, VINTID_0x29), VERSION_RANGE(100, 110), "OUT1000",
	  "12-bit Voltage Output Phidget",  {
		{PHIDCHUID_OUT1000_VOLTAGEOUTPUT_100,	PHIDCHCLASS_VOLTAGEOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Output"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_OUT1000_Failsafe, PHIDID_OUT1000, VINTID_0x29), VERSION_RANGE(110, 200),
	  "OUT1000", "12-bit Voltage Output Phidget",  {
		{PHIDCHUID_OUT1000_VOLTAGEOUTPUT_110,	PHIDCHCLASS_VOLTAGEOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Output"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_OUT1001, PHIDID_OUT1001, VINTID_0x2a), VERSION_RANGE(100, 110), "OUT1001",
	  "Isolated 12-bit Voltage Output Phidget",  {
		{PHIDCHUID_OUT1001_VOLTAGEOUTPUT_100,	PHIDCHCLASS_VOLTAGEOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Output"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_OUT1001_Failsafe, PHIDID_OUT1001, VINTID_0x2a), VERSION_RANGE(110, 200),
	  "OUT1001", "Isolated 12-bit Voltage Output Phidget",  {
		{PHIDCHUID_OUT1001_VOLTAGEOUTPUT_110,	PHIDCHCLASS_VOLTAGEOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Output"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_OUT1002, PHIDID_OUT1002, VINTID_0x2b), VERSION_RANGE(100, 110), "OUT1002",
	  "Isolated 16-bit Voltage Output Phidget",  {
		{PHIDCHUID_OUT1002_VOLTAGEOUTPUT_100,	PHIDCHCLASS_VOLTAGEOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Output"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_OUT1002_Failsafe, PHIDID_OUT1002, VINTID_0x2b), VERSION_RANGE(110, 200),
	  "OUT1002", "Isolated 16-bit Voltage Output Phidget",  {
		{PHIDCHUID_OUT1002_VOLTAGEOUTPUT_110,	PHIDCHCLASS_VOLTAGEOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Output"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DAQ1200, PHIDID_DAQ1200, VINTID_0x1c), VERSION_RANGE(100, 200), "DAQ1200",
	  "4x Digital Input Phidget",  {
		{PHIDCHUID_DAQ1200_DIGITALINPUT_100,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Digital Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_OUT1100, PHIDID_OUT1100, VINTID_0x19), VERSION_RANGE(100, 110), "OUT1100",
	  "4x Digital Output Phidget",  {
		{PHIDCHUID_OUT1100_DIGITALOUTPUT_100,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_DUTY_CYCLE,	INDEX(0),	COUNT(4),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_OUT1100_Failsafe, PHIDID_OUT1100, VINTID_0x19), VERSION_RANGE(110, 120),
	  "OUT1100", "4x Digital Output Phidget",  {
		{PHIDCHUID_OUT1100_DIGITALOUTPUT_110,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_DUTY_CYCLE,	INDEX(0),	COUNT(4),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_OUT1100_Failsafe_Frequency, PHIDID_OUT1100, VINTID_0x19), VERSION_RANGE(120,
	  200), "OUT1100", "4x Digital Output Phidget",  {
		{PHIDCHUID_OUT1100_DIGITALOUTPUT_120,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_FREQUENCY,	INDEX(0),	COUNT(4),	EXCLUSIVE(-1),	"Digital Output"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DAQ1300, PHIDID_DAQ1300, VINTID_0x20), VERSION_RANGE(100, 200), "DAQ1300",
	  "4x Isolated Digital Input Phidget",  {
		{PHIDCHUID_DAQ1300_DIGITALINPUT_100,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Digital Input Isolated"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DAQ1301, PHIDID_DAQ1301, VINTID_0x36), VERSION_RANGE(100, 200), "DAQ1301",
	  "16x Isolated Digital Input Phidget",  {
		{PHIDCHUID_DAQ1301_DIGITALINPUT_100,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(16),	EXCLUSIVE(-1),	"Digital Input Isolated"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DAQ1400, PHIDID_DAQ1400, VINTID_0x22), VERSION_RANGE(100, 120), "DAQ1400",
	  "Versatile Input Phidget",  {
		{PHIDCHUID_DAQ1400_VOLTAGEINPUT_100,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{PHIDCHUID_DAQ1400_CURRENTINPUT_100,	PHIDCHCLASS_CURRENTINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Current Input"},
		{PHIDCHUID_DAQ1400_DIGITALINPUT_100,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_DAQ1400_FREQUENCYCOUNTER_100,	PHIDCHCLASS_FREQUENCYCOUNTER,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Frequency Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DAQ1400_120, PHIDID_DAQ1400, VINTID_0x22), VERSION_RANGE(120, 200), "DAQ1400",
	  "Versatile Input Phidget",  {
		{PHIDCHUID_DAQ1400_VOLTAGEINPUT_120,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{PHIDCHUID_DAQ1400_CURRENTINPUT_120,	PHIDCHCLASS_CURRENTINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Current Input"},
		{PHIDCHUID_DAQ1400_DIGITALINPUT_120,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Digital Input"},
		{PHIDCHUID_DAQ1400_FREQUENCYCOUNTER_120,	PHIDCHCLASS_FREQUENCYCOUNTER,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Frequency Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DAQ1500, PHIDID_DAQ1500, VINTID_0x18), VERSION_RANGE(100, 200), "DAQ1500",
	  "Wheatstone Bridge Phidget",  {
		{PHIDCHUID_DAQ1500_VOLTAGERATIOINPUT_100,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_BRIDGE,	INDEX(0),	COUNT(2),	EXCLUSIVE(-1),	"Bridge Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_VCP1100, PHIDID_VCP1100, VINTID_0x40), VERSION_RANGE(100, 200), "VCP1100",
	  "30A Current Sensor Phidget",  {
		{PHIDCHUID_VCP1100_CURRENTINPUT_100,	PHIDCHCLASS_CURRENTINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Current Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_VCP1100_1, PHIDID_VCP1100, VINTID_0x90), VERSION_RANGE(200, 300), "VCP1100",
	  "30A Current Sensor Phidget",  {
		{PHIDCHUID_VCP1100_CURRENTINPUT_200,	PHIDCHCLASS_CURRENTINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Current Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DCC1000, PHIDID_DCC1000, VINTID_0x2f), VERSION_RANGE(100, 200), "DCC1000",
	  "DC Motor Phidget",  {
		{PHIDCHUID_DCC1000_DCMOTOR_100,	PHIDCHCLASS_DCMOTOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"DC Motor Controller"},
		{PHIDCHUID_DCC1000_ENCODER_100,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_ENCODER_MODE_SETTABLE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Encoder Input"},
		{PHIDCHUID_DCC1000_VOLTAGERATIOINPUT_100,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Voltage Ratio"},
		{PHIDCHUID_DCC1000_TEMPERATURESENSOR_IC_100,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor"},
		{PHIDCHUID_DCC1000_CURRENTINPUT_100,	PHIDCHCLASS_CURRENTINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Current Sensor"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DCC1000_POSITIONCONTROL, PHIDID_DCC1000, VINTID_0x2f), VERSION_RANGE(200, 210),
	  "DCC1000", "DC Motor Phidget",  {
		{PHIDCHUID_DCC1000_DCMOTOR_200,	PHIDCHCLASS_DCMOTOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(0),	"DC Motor Controller"},
		{PHIDCHUID_DCC1000_ENCODER_200,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_ENCODER_MODE_SETTABLE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Encoder Input"},
		{PHIDCHUID_DCC1000_VOLTAGERATIOINPUT_200,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Voltage Ratio"},
		{PHIDCHUID_DCC1000_TEMPERATURESENSOR_IC_200,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor"},
		{PHIDCHUID_DCC1000_CURRENTINPUT_200,	PHIDCHCLASS_CURRENTINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Current Sensor"},
		{PHIDCHUID_DCC1000_MOTORPOSITIONCONTROLLER_200,	PHIDCHCLASS_MOTORPOSITIONCONTROLLER,
		 	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),	EXCLUSIVE(0),	"Position Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DCC1000_POSITIONCONTROL_FAILSAFE, PHIDID_DCC1000, VINTID_0x2f),
	  VERSION_RANGE(210, 300), "DCC1000", "DC Motor Phidget",  {
		{PHIDCHUID_DCC1000_DCMOTOR_210,	PHIDCHCLASS_DCMOTOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(0),	"DC Motor Controller"},
		{PHIDCHUID_DCC1000_ENCODER_210,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_ENCODER_MODE_SETTABLE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Encoder Input"},
		{PHIDCHUID_DCC1000_VOLTAGERATIOINPUT_210,	PHIDCHCLASS_VOLTAGERATIOINPUT,
		 	PHIDCHSUBCLASS_VOLTAGERATIOINPUT_SENSOR_PORT,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Voltage Ratio"},
		{PHIDCHUID_DCC1000_TEMPERATURESENSOR_IC_210,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor"},
		{PHIDCHUID_DCC1000_CURRENTINPUT_210,	PHIDCHCLASS_CURRENTINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Current Sensor"},
		{PHIDCHUID_DCC1000_MOTORPOSITIONCONTROLLER_210,	PHIDCHCLASS_MOTORPOSITIONCONTROLLER,
		 	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),	EXCLUSIVE(0),	"Position Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DCC1001, PHIDID_DCC1001, VINTID_0x44), VERSION_RANGE(100, 120), "DCC1001",
	  "2A DC Motor Phidget",  {
		{PHIDCHUID_DCC1001_DCMOTOR_100,	PHIDCHCLASS_DCMOTOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(0),	"DC Motor Controller"},
		{PHIDCHUID_DCC1001_ENCODER_100,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Encoder Input"},
		{PHIDCHUID_DCC1001_MOTORPOSITIONCONTROLLER_100,	PHIDCHCLASS_MOTORPOSITIONCONTROLLER,
		 	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),	EXCLUSIVE(0),	"Position Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DCC1001_Failsafe, PHIDID_DCC1001, VINTID_0x44), VERSION_RANGE(120, 200),
	  "DCC1001", "2A DC Motor Phidget",  {
		{PHIDCHUID_DCC1001_DCMOTOR_120,	PHIDCHCLASS_DCMOTOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(0),	"DC Motor Controller"},
		{PHIDCHUID_DCC1001_ENCODER_120,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Encoder Input"},
		{PHIDCHUID_DCC1001_MOTORPOSITIONCONTROLLER_120,	PHIDCHCLASS_MOTORPOSITIONCONTROLLER,
		 	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),	EXCLUSIVE(0),	"Position Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DCC1002, PHIDID_DCC1002, VINTID_0x46), VERSION_RANGE(100, 110), "DCC1002",
	  "4A DC Motor Phidget",  {
		{PHIDCHUID_DCC1002_DCMOTOR_100,	PHIDCHCLASS_DCMOTOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(0),	"DC Motor Controller"},
		{PHIDCHUID_DCC1002_ENCODER_100,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Encoder Input"},
		{PHIDCHUID_DCC1002_MOTORPOSITIONCONTROLLER_100,	PHIDCHCLASS_MOTORPOSITIONCONTROLLER,
		 	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),	EXCLUSIVE(0),	"Position Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DCC1002_Failsafe, PHIDID_DCC1002, VINTID_0x46), VERSION_RANGE(110, 200),
	  "DCC1002", "4A DC Motor Phidget",  {
		{PHIDCHUID_DCC1002_DCMOTOR_110,	PHIDCHCLASS_DCMOTOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(0),	"DC Motor Controller"},
		{PHIDCHUID_DCC1002_ENCODER_110,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Encoder Input"},
		{PHIDCHUID_DCC1002_MOTORPOSITIONCONTROLLER_110,	PHIDCHCLASS_MOTORPOSITIONCONTROLLER,
		 	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),	EXCLUSIVE(0),	"Position Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DCC1003, PHIDID_DCC1003, VINTID_0x49), VERSION_RANGE(100, 110), "DCC1003",
	  "2x DC Motor Phidget",  {
		{PHIDCHUID_DCC1003_DCMOTOR_100,	PHIDCHCLASS_DCMOTOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(2),
		 	EXCLUSIVE(-1),	"DC Motor Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DCC1003_Failsafe, PHIDID_DCC1003, VINTID_0x49), VERSION_RANGE(110, 200),
	  "DCC1003", "2x DC Motor Phidget",  {
		{PHIDCHUID_DCC1003_DCMOTOR_110,	PHIDCHCLASS_DCMOTOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(2),
		 	EXCLUSIVE(-1),	"DC Motor Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DCC1100, PHIDID_DCC1100, VINTID_0x41), VERSION_RANGE(100, 120), "DCC1100",
	  "Brushless DC Motor Phidget",  {
		{PHIDCHUID_DCC1100_BLDCMOTOR_100,	PHIDCHCLASS_BLDCMOTOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(0),	"Brushless DC Motor Controller"},
		{PHIDCHUID_DCC1100_TEMPERATURESENSOR_IC_100,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor"},
		{PHIDCHUID_DCC1100_MOTORPOSITIONCONTROLLER_100,	PHIDCHCLASS_MOTORPOSITIONCONTROLLER,
		 	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),	EXCLUSIVE(0),	"Position Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DCC1100_Failsafe, PHIDID_DCC1100, VINTID_0x41), VERSION_RANGE(120, 200),
	  "DCC1100", "Brushless DC Motor Phidget",  {
		{PHIDCHUID_DCC1100_BLDCMOTOR_120,	PHIDCHCLASS_BLDCMOTOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(0),	"Brushless DC Motor Controller"},
		{PHIDCHUID_DCC1100_TEMPERATURESENSOR_IC_120,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor"},
		{PHIDCHUID_DCC1100_MOTORPOSITIONCONTROLLER_120,	PHIDCHCLASS_MOTORPOSITIONCONTROLLER,
		 	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),	EXCLUSIVE(0),	"Position Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DST1000, PHIDID_DST1000, VINTID_0x2d), VERSION_RANGE(100, 200), "DST1000",
	  "Distance Phidget",  {
		{PHIDCHUID_DST1000_DISTANCESENSOR_100,	PHIDCHCLASS_DISTANCESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Distance Sensor 200mm"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DST1001, PHIDID_DST1001, VINTID_0x79), VERSION_RANGE(100, 200), "DST1001",
	  "Distance Phidget 650mm",  {
		{PHIDCHUID_DST1001_DISTANCESENSOR_100,	PHIDCHCLASS_DISTANCESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Distance Sensor 650mm"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DST1002, PHIDID_DST1002, VINTID_0x7e), VERSION_RANGE(100, 200), "DST1002",
	  "Distance Phidget 1300mm",  {
		{PHIDCHUID_DST1002_DISTANCESENSOR_100,	PHIDCHCLASS_DISTANCESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Distance Sensor 1300mm"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_DST1200, PHIDID_DST1200, VINTID_0x2e), VERSION_RANGE(100, 200), "DST1200",
	  "Sonar Phidget",  {
		{PHIDCHUID_DST1200_DISTANCESENSOR_100,	PHIDCHCLASS_DISTANCESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Sonar Distance Sensor"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_ENC1000, PHIDID_ENC1000, VINTID_0x12), VERSION_RANGE(100, 200), "ENC1000",
	  "Quadrature Encoder Phidget",  {
		{PHIDCHUID_ENC1000_ENCODER_100,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_ENCODER_MODE_SETTABLE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Encoder Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_HIN1101, PHIDID_HIN1101, VINTID_0x43), VERSION_RANGE(100, 200), "HIN1101",
	  "Phidget Dial",  {
		{PHIDCHUID_HIN1101_ENCODER_100,	PHIDCHCLASS_ENCODER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Encoder Input"},
		{PHIDCHUID_HIN1101_DIGITALINPUT_100,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Digital Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_HIN1000, PHIDID_HIN1000, VINTID_0x24), VERSION_RANGE(100, 200), "HIN1000",
	  "Touch Keypad Phidget",  {
		{PHIDCHUID_HIN1000_CAPACITIVETOUCH_100,	PHIDCHCLASS_CAPACITIVETOUCH,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(7),	EXCLUSIVE(-1),	"Capacitive Touch Sensor"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_HIN1001, PHIDID_HIN1001, VINTID_0x38), VERSION_RANGE(100, 200), "HIN1001",
	  "Touch Wheel Phidget",  {
		{PHIDCHUID_HIN1001_CAPACITIVETOUCH_BUTTONS_100,	PHIDCHCLASS_CAPACITIVETOUCH,
		 	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(4),	EXCLUSIVE(-1),	"Capacitive Touch Sensor"},
		{PHIDCHUID_HIN1001_CAPACITIVETOUCH_WHEEL_100,	PHIDCHCLASS_CAPACITIVETOUCH,	PHIDCHSUBCLASS_NONE,
		 	INDEX(4),	COUNT(1),	EXCLUSIVE(-1),	"Capacitive Scroll Wheel"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_HIN1100, PHIDID_HIN1100, VINTID_0x25), VERSION_RANGE(100, 200), "HIN1100",
	  "Thumbstick Phidget",  {
		{PHIDCHUID_HIN1100_VOLTAGERATIOINPUT_100,	PHIDCHCLASS_VOLTAGERATIOINPUT,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(2),	EXCLUSIVE(-1),	"Thumbstick Axis"},
		{PHIDCHUID_HIN1100_DIGITALINPUT_100,	PHIDCHCLASS_DIGITALINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Thumbstick Button"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_HUM1000, PHIDID_HUM1000, VINTID_0x14), VERSION_RANGE(100, 200), "HUM1000",
	  "Humidity Phidget",  {
		{PHIDCHUID_HUM1000_HUMIDITYSENSOR_100,	PHIDCHCLASS_HUMIDITYSENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Humidity Sensor"},
		{PHIDCHUID_HUM1000_TEMPERATURESENSOR_IC_100,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_HUM1001, PHIDID_HUM1001, VINTID_0x7f), VERSION_RANGE(100, 200), "HUM1001",
	  "Humidity Phidget",  {
		{PHIDCHUID_HUM1001_HUMIDITYSENSOR_100,	PHIDCHCLASS_HUMIDITYSENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Humidity Sensor"},
		{PHIDCHUID_HUM1001_TEMPERATURESENSOR_IC_100,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_LCD1100, PHIDID_LCD1100, VINTID_0x28), VERSION_RANGE(100, 200), "LCD1100",
	  "Graphic LCD Phidget",  {
		{PHIDCHUID_LCD1100_LCD_100,	PHIDCHCLASS_LCD,	PHIDCHSUBCLASS_LCD_GRAPHIC,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Graphic LCD"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_LED1000, PHIDID_LED1000, VINTID_0x27), VERSION_RANGE(100, 200), "LED1000",
	  "32x Isolated LED Phidget",  {
		{PHIDCHUID_LED1000_DIGITALOUTPUT_100,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_LED_DRIVER,	INDEX(0),	COUNT(32),	EXCLUSIVE(-1),	"LED Driver"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_LUX1000, PHIDID_LUX1000, VINTID_0x21), VERSION_RANGE(100, 200), "LUX1000",
	  "Light Phidget",  {
		{PHIDCHUID_LUX1000_LIGHTSENSOR_100,	PHIDCHCLASS_LIGHTSENSOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Light Sensor"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_HUM1100, PHIDID_HUM1100, VINTID_0x88), VERSION_RANGE(100, 200), "HUM1100",
	  "Soil Moisture Phidget",  {
		{PHIDCHUID_HUM1100_VOLTAGERATIOINPUT_100,	PHIDCHCLASS_VOLTAGERATIOINPUT,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Moisture Sensor"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_MOT1100, PHIDID_MOT1100, VINTID_0x33), VERSION_RANGE(200, 300), "MOT1100",
	  "Accelerometer Phidget",  {
		{PHIDCHUID_MOT1100_ACCELEROMETER_200,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Accelerometer"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_MOT1101, PHIDID_MOT1101, VINTID_0x34), VERSION_RANGE(100, 200), "MOT1101",
	  "Spatial Phidget",  {
		{PHIDCHUID_MOT1101_ACCELEROMETER_100,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Accelerometer"},
		{PHIDCHUID_MOT1101_GYROSCOPE_100,	PHIDCHCLASS_GYROSCOPE,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Gyroscope"},
		{PHIDCHUID_MOT1101_MAGNETOMETER_100,	PHIDCHCLASS_MAGNETOMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Magnetometer"},
		{PHIDCHUID_MOT1101_SPATIAL_100,	PHIDCHCLASS_SPATIAL,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Spatial"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_MOT1102, PHIDID_MOT1102, VINTID_0x89), VERSION_RANGE(200, 300), "MOT1102",
	  "Spatial Phidget",  {
		{PHIDCHUID_MOT1102_ACCELEROMETER_200,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Accelerometer"},
		{PHIDCHUID_MOT1102_GYROSCOPE_200,	PHIDCHCLASS_GYROSCOPE,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Gyroscope"},
		{PHIDCHUID_MOT1102_MAGNETOMETER_200,	PHIDCHCLASS_MAGNETOMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Magnetometer"},
		{PHIDCHUID_MOT1102_SPATIAL_200,	PHIDCHCLASS_SPATIAL,	PHIDCHSUBCLASS_SPATIAL_AHRS,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Spatial"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_MOT0109, PHIDID_MOT0109, PHIDCLASS_SPATIAL, USBVID_PHIDGETS, USBID_0x8c, 0, 0,
	  spatial, 3, 3, 3, 1, 1),
	  VERSION_RANGE(100, 200), "MOT0109", "PhidgetSpatial Precision 3/3/3",  {
		{PHIDCHUID_MOT0109_ACCELEROMETER_100,	PHIDCHCLASS_ACCELEROMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Accelerometer"},
		{PHIDCHUID_MOT0109_GYROSCOPE_100,	PHIDCHCLASS_GYROSCOPE,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Gyroscope"},
		{PHIDCHUID_MOT0109_MAGNETOMETER_100,	PHIDCHCLASS_MAGNETOMETER,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"3-Axis Magnetometer"},
		{PHIDCHUID_MOT0109_SPATIAL_100,	PHIDCHCLASS_SPATIAL,	PHIDCHSUBCLASS_SPATIAL_AHRS,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Spatial"},
		{PHIDCHUID_MOT0109_TEMPERATURESENSOR_100,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_PRE1000, PHIDID_PRE1000, VINTID_0x11), VERSION_RANGE(100, 200), "PRE1000",
	  "Barometer Phidget",  {
		{PHIDCHUID_PRE1000_PRESSURESENSOR_100,	PHIDCHCLASS_PRESSURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Barometer"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_RCC1000, PHIDID_RCC1000, VINTID_0x31), VERSION_RANGE(100, 110), "RCC1000",
	  "16x RC Servo Phidget",  {
		{PHIDCHUID_RCC1000_RCSERVO_100,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(16),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_RCC1000_Failsafe, PHIDID_RCC1000, VINTID_0x31), VERSION_RANGE(110, 200),
	  "RCC1000", "16x RC Servo Phidget",  {
		{PHIDCHUID_RCC1000_RCSERVO_110,	PHIDCHCLASS_RCSERVO,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(16),
		 	EXCLUSIVE(-1),	"RC Servo Motor Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_REL1000, PHIDID_REL1000, VINTID_0x2c), VERSION_RANGE(100, 110), "REL1000",
	  "4x Relay Phidget",  {
		{PHIDCHUID_REL1000_DIGITALOUTPUT_100,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Power Relay"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_REL1000_Failsafe, PHIDID_REL1000, VINTID_0x2c), VERSION_RANGE(110, 200),
	  "REL1000", "4x Relay Phidget",  {
		{PHIDCHUID_REL1000_DIGITALOUTPUT_110,	PHIDCHCLASS_DIGITALOUTPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Power Relay"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_REL1100, PHIDID_REL1100, VINTID_0x1a), VERSION_RANGE(100, 110), "REL1100",
	  "4x Isolated Solid State Relay Phidget",  {
		{PHIDCHUID_REL1100_DIGITALOUTPUT_100,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_DUTY_CYCLE,	INDEX(0),	COUNT(4),	EXCLUSIVE(-1),	"Digital Output Isolated"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_REL1100_Failsafe, PHIDID_REL1100, VINTID_0x1a), VERSION_RANGE(110, 120),
	  "REL1100", "4x Isolated Solid State Relay Phidget",  {
		{PHIDCHUID_REL1100_DIGITALOUTPUT_110,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_DUTY_CYCLE,	INDEX(0),	COUNT(4),	EXCLUSIVE(-1),	"Digital Output Isolated"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_REL1100_Failsafe_Frequency, PHIDID_REL1100, VINTID_0x1a), VERSION_RANGE(120,
	  200), "REL1100", "4x Isolated Solid State Relay Phidget",  {
		{PHIDCHUID_REL1100_DIGITALOUTPUT_120,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_FREQUENCY,	INDEX(0),	COUNT(4),	EXCLUSIVE(-1),	"Digital Output Isolated"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_REL1101, PHIDID_REL1101, VINTID_0x1b), VERSION_RANGE(100, 110), "REL1101",
	  "16x Isolated Solid State Relay Phidget",  {
		{PHIDCHUID_REL1101_DIGITALOUTPUT_100,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_DUTY_CYCLE,	INDEX(0),	COUNT(16),	EXCLUSIVE(-1),	"Digital Output Isolated"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_REL1101_Failsafe, PHIDID_REL1101, VINTID_0x1b), VERSION_RANGE(110, 200),
	  "REL1101", "16x Isolated Solid State Relay Phidget",  {
		{PHIDCHUID_REL1101_DIGITALOUTPUT_110,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_DUTY_CYCLE,	INDEX(0),	COUNT(16),	EXCLUSIVE(-1),	"Digital Output Isolated"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_REL1101_1, PHIDID_REL1101, VINTID_0x82), VERSION_RANGE(100, 300), "REL1101",
	  "16x Isolated Solid State Relay Phidget",  {
		{PHIDCHUID_REL1101_1_DIGITALOUTPUT_FREQ_100,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_FREQUENCY,	INDEX(0),	COUNT(8),	EXCLUSIVE(-1),	"Digital Output Isolated Frequency Control"},
		{PHIDCHUID_REL1101_1_DIGITALOUTPUT_100,	PHIDCHCLASS_DIGITALOUTPUT,
		 	PHIDCHSUBCLASS_DIGITALOUTPUT_DUTY_CYCLE,	INDEX(8),	COUNT(8),	EXCLUSIVE(-1),	"Digital Output Isolated"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_SAF1000, PHIDID_SAF1000, VINTID_0x26), VERSION_RANGE(100, 110), "SAF1000",
	  "Programmable Power Guard Phidget",  {
		{PHIDCHUID_SAF1000_POWERGUARD_100,	PHIDCHCLASS_POWERGUARD,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Power Supply Protector"},
		{PHIDCHUID_SAF1000_VOLTAGEINPUT_100,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Sensor"},
		{PHIDCHUID_SAF1000_TEMPERATURESENSOR_IC_100,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_SAF1000_Failsafe, PHIDID_SAF1000, VINTID_0x26), VERSION_RANGE(110, 200),
	  "SAF1000", "Programmable Power Guard Phidget",  {
		{PHIDCHUID_SAF1000_POWERGUARD_110,	PHIDCHCLASS_POWERGUARD,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Power Supply Protector"},
		{PHIDCHUID_SAF1000_VOLTAGEINPUT_110,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Sensor"},
		{PHIDCHUID_SAF1000_TEMPERATURESENSOR_IC_110,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_SND1000, PHIDID_SND1000, VINTID_0x23), VERSION_RANGE(100, 200), "SND1000",
	  "Sound Phidget",  {
		{PHIDCHUID_SND1000_SOUNDSENSOR_100,	PHIDCHCLASS_SOUNDSENSOR,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Sound Sensor"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_STC1000, PHIDID_STC1000, VINTID_0x30), VERSION_RANGE(100, 110), "STC1000",
	  "Stepper Phidget",  {
		{PHIDCHUID_STC1000_STEPPER_100,	PHIDCHCLASS_STEPPER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Bipolar Stepper Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_STC1000_Failsafe, PHIDID_STC1000, VINTID_0x30), VERSION_RANGE(110, 200),
	  "STC1000", "Stepper Phidget",  {
		{PHIDCHUID_STC1000_STEPPER_110,	PHIDCHCLASS_STEPPER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Bipolar Stepper Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_STC1001, PHIDID_STC1001, VINTID_0x45), VERSION_RANGE(100, 110), "STC1001",
	  "2.5A Stepper Phidget",  {
		{PHIDCHUID_STC1001_STEPPER_100,	PHIDCHCLASS_STEPPER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Bipolar Stepper Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_STC1001_Failsafe, PHIDID_STC1001, VINTID_0x45), VERSION_RANGE(110, 200),
	  "STC1001", "2.5A Stepper Phidget",  {
		{PHIDCHUID_STC1001_STEPPER_110,	PHIDCHCLASS_STEPPER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Bipolar Stepper Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_STC1002, PHIDID_STC1002, VINTID_0x47), VERSION_RANGE(100, 110), "STC1002",
	  "8A Stepper Phidget",  {
		{PHIDCHUID_STC1002_STEPPER_100,	PHIDCHCLASS_STEPPER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Bipolar Stepper Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_STC1002_Failsafe, PHIDID_STC1002, VINTID_0x47), VERSION_RANGE(110, 200),
	  "STC1002", "8A Stepper Phidget",  {
		{PHIDCHUID_STC1002_STEPPER_110,	PHIDCHCLASS_STEPPER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Bipolar Stepper Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_STC1003, PHIDID_STC1003, VINTID_0x48), VERSION_RANGE(100, 110), "STC1003",
	  "4A Stepper Phidget",  {
		{PHIDCHUID_STC1003_STEPPER_100,	PHIDCHCLASS_STEPPER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Bipolar Stepper Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_STC1003_Failsafe, PHIDID_STC1003, VINTID_0x48), VERSION_RANGE(110, 200),
	  "STC1003", "4A Stepper Phidget",  {
		{PHIDCHUID_STC1003_STEPPER_110,	PHIDCHCLASS_STEPPER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Bipolar Stepper Controller"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_STC1003_1, PHIDID_STC1003, VINTID_0x8e), VERSION_RANGE(200, 300), "STC1003",
	  "4A Stepper Phidget",  {
		{PHIDCHUID_STC1003_STEPPER_200,	PHIDCHCLASS_STEPPER,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Bipolar Stepper Controller"},
		{PHIDCHUID_STC1003_VOLTAGEINPUT_200,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_TMP1000, PHIDID_TMP1000, VINTID_0x13), VERSION_RANGE(100, 200), "TMP1000",
	  "Temperature Phidget",  {
		{PHIDCHUID_TMP1000_TEMPERATURESENSOR_IC_100,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor (IC)"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_TMP1100, PHIDID_TMP1100, VINTID_0x37), VERSION_RANGE(100, 200), "TMP1100",
	  "Isolated Thermocouple Phidget",  {
		{PHIDCHUID_TMP1100_TEMPERATURESENSOR_THERMOCOUPLE_100,	PHIDCHCLASS_TEMPERATURESENSOR,
		 	PHIDCHSUBCLASS_TEMPERATURESENSOR_THERMOCOUPLE,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Thermocouple Input"},
		{PHIDCHUID_TMP1100_TEMPERATURESENSOR_IC_100,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(1),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor (IC)"},
		{PHIDCHUID_TMP1100_VOLTAGEINPUT_100,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_TMP1101, PHIDID_TMP1101, VINTID_0x15), VERSION_RANGE(100, 200), "TMP1101",
	  "4x Thermocouple Phidget",  {
		{PHIDCHUID_TMP1101_TEMPERATURESENSOR_THERMOCOUPLE_100,	PHIDCHCLASS_TEMPERATURESENSOR,
		 	PHIDCHSUBCLASS_TEMPERATURESENSOR_THERMOCOUPLE,	INDEX(0),	COUNT(4),	EXCLUSIVE(-1),	"Thermocouple Input"},
		{PHIDCHUID_TMP1101_TEMPERATURESENSOR_IC_100,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(4),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor (IC)"},
		{PHIDCHUID_TMP1101_VOLTAGEINPUT_100,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_TMP1101_1, PHIDID_TMP1101, VINTID_0x8f), VERSION_RANGE(200, 300), "TMP1101",
	  "4x Thermocouple Phidget",  {
		{PHIDCHUID_TMP1101_TEMPERATURESENSOR_THERMOCOUPLE_200,	PHIDCHCLASS_TEMPERATURESENSOR,
		 	PHIDCHSUBCLASS_TEMPERATURESENSOR_THERMOCOUPLE,	INDEX(0),	COUNT(4),	EXCLUSIVE(-1),	"Thermocouple Input"},
		{PHIDCHUID_TMP1101_TEMPERATURESENSOR_IC_200,	PHIDCHCLASS_TEMPERATURESENSOR,	PHIDCHSUBCLASS_NONE,
		 	INDEX(4),	COUNT(1),	EXCLUSIVE(-1),	"Temperature Sensor (IC)"},
		{PHIDCHUID_TMP1101_VOLTAGEINPUT_200,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(4),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_TMP1200, PHIDID_TMP1200, VINTID_0x10), VERSION_RANGE(100, 200), "TMP1200",
	  "RTD Phidget",  {
		{PHIDCHUID_TMP1200_TEMPERATURESENSOR_RTD_100,	PHIDCHCLASS_TEMPERATURESENSOR,
		 	PHIDCHSUBCLASS_TEMPERATURESENSOR_RTD,	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"RTD input"},
		{PHIDCHUID_TMP1200_RESISTANCEINPUT_100,	PHIDCHCLASS_RESISTANCEINPUT,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Resistance Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_VCP1000, PHIDID_VCP1000, VINTID_0x35), VERSION_RANGE(100, 200), "VCP1000",
	  "20-bit (+-40V) Voltage Input Phidget",  {
		{PHIDCHUID_VCP1000_VOLTAGEINPUT_100,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_VCP1001, PHIDID_VCP1001, VINTID_0x1f), VERSION_RANGE(100, 110), "VCP1001",
	  "10-bit (+-40V) Voltage Input Phidget",  {
		{PHIDCHUID_VCP1001_VOLTAGEINPUT_100,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_VCP1001_110, PHIDID_VCP1001, VINTID_0x1f), VERSION_RANGE(110, 200), "VCP1001",
	  "10-bit (+-40V) Voltage Input Phidget",  {
		{PHIDCHUID_VCP1001_VOLTAGEINPUT_110,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_VCP1002, PHIDID_VCP1002, VINTID_0x1e), VERSION_RANGE(100, 110), "VCP1002",
	  "10-bit (+-1V) Voltage Input Phidget",  {
		{PHIDCHUID_VCP1002_VOLTAGEINPUT_100,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_VCP1002_110, PHIDID_VCP1002, VINTID_0x1e), VERSION_RANGE(110, 200), "VCP1002",
	  "10-bit (+-1V) Voltage Input Phidget",  {
		{PHIDCHUID_VCP1002_VOLTAGEINPUT_110,	PHIDCHCLASS_VOLTAGEINPUT,	PHIDCHSUBCLASS_NONE,	INDEX(0),
		 	COUNT(1),	EXCLUSIVE(-1),	"Voltage Input"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_HUB0000, PHIDID_HUB0000, PHIDCLASS_HUB, USBVID_PHIDGETS, USBID_0x3f, 0, 1, hub,
	  6, 4),
	  VERSION_RANGE(100, 200), "HUB0000", "6-Port USB VINT Hub Phidget",  {
		{PHIDCHUID_HUB0000_HUB_100,	PHIDCHCLASS_HUB,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"VINT Hub"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_HUB0000_PHIDUSB, PHIDID_HUB0000, PHIDCLASS_HUB, USBVID_PHIDGETS, USBID_0x3f, 0,
	  0, hub, 6, 4),
	  VERSION_RANGE(300, 400), "HUB0000", "6-Port USB VINT Hub Phidget",  {
		{PHIDCHUID_HUB0000_HUB_300,	PHIDCHCLASS_HUB,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"VINT Hub"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_HUB0001, PHIDID_HUB0001, PHIDCLASS_HUB, USBVID_PHIDGETS, USBID_0x43, 0, 0, hub,
	  6, 4),
	  VERSION_RANGE(100, 200), "HUB0001", "6-Port USB VINT Hub Phidget",  {
		{PHIDCHUID_HUB0001_HUB_100,	PHIDCHCLASS_HUB,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"VINT Hub"},
		{END_OF_LIST}
	}},
	{SPI_PHIDGET(PHIDUID_HUB0004, PHIDID_HUB0004, PHIDCLASS_HUB, SPIID_0x1, hub, 6, 4),
	  VERSION_RANGE(100, 200), "HUB0004", "6-Port PhidgetSBC VINT Hub Phidget",  {
		{PHIDCHUID_HUB0004_HUB_100,	PHIDCHCLASS_HUB,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"VINT Hub"},
		{END_OF_LIST}
	}},
	{SPI_PHIDGET(PHIDUID_HUB0004_BADPORT, PHIDID_HUB0004, PHIDCLASS_HUB, SPIID_0x1, hub, 6, 4),
	  VERSION_RANGE(200, 300), "HUB0004", "6-Port PhidgetSBC VINT Hub Phidget",  {
		{PHIDCHUID_HUB0004_HUB_200,	PHIDCHCLASS_HUB,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"VINT Hub"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_HUB5000, PHIDID_HUB5000, PHIDCLASS_HUB, USBVID_PHIDGETS, USBID_0x42, 0, 1, hub,
	  6, 4),
	  VERSION_RANGE(100, 200), "HUB5000", "6-Port Network VINT Hub Phidget",  {
		{PHIDCHUID_HUB5000_HUB_100,	PHIDCHCLASS_HUB,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"VINT Hub"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_HUB5000_PHIDUSB, PHIDID_HUB5000, PHIDCLASS_HUB, USBVID_PHIDGETS, USBID_0x42, 0,
	  0, hub, 6, 4),
	  VERSION_RANGE(200, 300), "HUB5000", "6-Port Network VINT Hub Phidget",  {
		{PHIDCHUID_HUB5000_HUB_200,	PHIDCHCLASS_HUB,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"VINT Hub"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_FIRMWARE_UPGRADE_M3_USB, PHIDID_FIRMWARE_UPGRADE_USB, PHIDCLASS_FIRMWAREUPGRADE,
	  USBVID_PHIDGETS, USBID_0x98, 0, 0, dummy, 0, 0, 0),
	  VERSION_RANGE(0, 9999), "FIRMWARE_UPGRADE_M3", "USB Firmware Upgrade (NXP M3)",  {
		{PHIDCHUID_M3_USB_FIRMWARE_UPGRADE_000,	PHIDCHCLASS_FIRMWAREUPGRADE,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Firmware Upgrade"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_FIRMWARE_UPGRADE_STM32_USB, PHIDID_FIRMWARE_UPGRADE_USB,
	  PHIDCLASS_FIRMWAREUPGRADE, USBVID_PHIDGETS, USBID_0x9c, 0, 0, dummy, 0, 0, 0),
	  VERSION_RANGE(100, 200), "FIRMWARE_UPGRADE_STM32_USB", "USB Firmware Upgrade (STM32)",  {
		{PHIDCHUID_STM32_USB_FIRMWARE_UPGRADE_100,	PHIDCHCLASS_FIRMWAREUPGRADE,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Firmware Upgrade"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_FIRMWARE_UPGRADE_STM32F0, PHIDID_FIRMWARE_UPGRADE_STM32F0, VINTID_0xffd),
	  VERSION_RANGE(100, 110), "FIRMWARE_UPGRADE_STM32F0", "VINT Firmware Upgrade (STM32F0)",  {
		{PHIDCHUID_STM32F0_FIRMWARE_UPGRADE_100,	PHIDCHCLASS_FIRMWAREUPGRADE,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Firmware Upgrade"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_FIRMWARE_UPGRADE_STM32G0, PHIDID_FIRMWARE_UPGRADE_STM32G0, VINTID_0xffd),
	  VERSION_RANGE(110, 200), "FIRMWARE_UPGRADE_STM32G0", "VINT Firmware Upgrade (STM32G0)",  {
		{PHIDCHUID_STM32G0_FIRMWARE_UPGRADE_110,	PHIDCHCLASS_FIRMWAREUPGRADE,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Firmware Upgrade"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_FIRMWARE_UPGRADE_STM8S, PHIDID_FIRMWARE_UPGRADE_STM8S, VINTID_0xffe),
	  VERSION_RANGE(100, 200), "FIRMWARE_UPGRADE_STM8S", "VINT Firmware Upgrade (STM8S)",  {
		{PHIDCHUID_STM8S_FIRMWARE_UPGRADE_100,	PHIDCHCLASS_FIRMWAREUPGRADE,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Firmware Upgrade"},
		{END_OF_LIST}
	}},
	{SPI_PHIDGET(PHIDUID_FIRMWARE_UPGRADE_M3_SPI, PHIDID_FIRMWARE_UPGRADE_SPI, PHIDCLASS_FIRMWAREUPGRADE,
	  SPIID_0x2, dummy, 0),
	  VERSION_RANGE(0, 9999), "FIRMWARE_UPGRADE_M3", "SPI Firmware Upgrade (M3)",  {
		{PHIDCHUID_M3_SPI_FIRMWARE_UPGRADE_000,	PHIDCHCLASS_FIRMWAREUPGRADE,	PHIDCHSUBCLASS_NONE,
		 	INDEX(0),	COUNT(1),	EXCLUSIVE(-1),	"Firmware Upgrade"},
		{END_OF_LIST}
	}},
	{VIRTUAL_PHIDGET(PHIDUID_DICTIONARY, PHIDID_DICTIONARY, PHIDCLASS_DICTIONARY, VIRTUALID_0x0),
	  VERSION_RANGE(100, 200), "Dictionary", "Dictionary",  {
		{PHIDCHUID_DICTIONARY,	PHIDCHCLASS_DICTIONARY,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Dictionary"},
		{END_OF_LIST}
	}},
	{USB_PHIDGET(PHIDUID_UNKNOWNUSB, PHIDID_UNKNOWN, PHIDCLASS_GENERIC, USBVID_PHIDGETS, USBID_0xaf, 0,
	  0, dummy, 0, 0, 0),
	  VERSION_RANGE(0, 9999), " ", "Unsupported USB Phidget",  {
		{PHIDCHUID_USB_UNKNOWN,	PHIDCHCLASS_GENERIC,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Unsupported USB Channel"},
		{END_OF_LIST}
	}},
	{VINT_PHIDGET(PHIDUID_UNKNOWNVINT, PHIDID_UNKNOWN, VINTID_0xff0), VERSION_RANGE(0, 9999), " ",
	  "Unsupported VINT Phidget",  {
		{PHIDCHUID_VINT_UNKNOWN,	PHIDCHCLASS_GENERIC,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Unsupported VINT Channel"},
		{END_OF_LIST}
	}},
	{SPI_PHIDGET(PHIDUID_UNKNOWNSPI, PHIDID_UNKNOWN, PHIDCLASS_GENERIC, SPIID_0xffff, dummy, 0, 0, 0),
	  VERSION_RANGE(0, 9999), " ", "Unsupported SPI Phidget",  {
		{PHIDCHUID_SPI_UNKNOWN,	PHIDCHCLASS_GENERIC,	PHIDCHSUBCLASS_NONE,	INDEX(0),	COUNT(1),
		 	EXCLUSIVE(-1),	"Unsupported SPI Channel"},
		{END_OF_LIST}
	}},
	{END_OF_LIST}
};

PhidgetReturnCode
createTypedPhidgetChannelHandle(PhidgetChannelHandle * channel, Phidget_ChannelClass class) {

	assert(channel);

	switch (class) {
	case PHIDCHCLASS_VOLTAGERATIOINPUT:
		return (PhidgetVoltageRatioInput_create((PhidgetVoltageRatioInputHandle*)channel));
	case PHIDCHCLASS_DIGITALINPUT:
		return (PhidgetDigitalInput_create((PhidgetDigitalInputHandle*)channel));
	case PHIDCHCLASS_DIGITALOUTPUT:
		return (PhidgetDigitalOutput_create((PhidgetDigitalOutputHandle*)channel));
	case PHIDCHCLASS_RCSERVO:
		return (PhidgetRCServo_create((PhidgetRCServoHandle*)channel));
	case PHIDCHCLASS_VOLTAGEOUTPUT:
		return (PhidgetVoltageOutput_create((PhidgetVoltageOutputHandle*)channel));
	case PHIDCHCLASS_ACCELEROMETER:
		return (PhidgetAccelerometer_create((PhidgetAccelerometerHandle*)channel));
	case PHIDCHCLASS_VOLTAGEINPUT:
		return (PhidgetVoltageInput_create((PhidgetVoltageInputHandle*)channel));
	case PHIDCHCLASS_CAPACITIVETOUCH:
		return (PhidgetCapacitiveTouch_create((PhidgetCapacitiveTouchHandle*)channel));
	case PHIDCHCLASS_RFID:
		return (PhidgetRFID_create((PhidgetRFIDHandle*)channel));
	case PHIDCHCLASS_GPS:
		return (PhidgetGPS_create((PhidgetGPSHandle*)channel));
	case PHIDCHCLASS_GYROSCOPE:
		return (PhidgetGyroscope_create((PhidgetGyroscopeHandle*)channel));
	case PHIDCHCLASS_MAGNETOMETER:
		return (PhidgetMagnetometer_create((PhidgetMagnetometerHandle*)channel));
	case PHIDCHCLASS_SPATIAL:
		return (PhidgetSpatial_create((PhidgetSpatialHandle*)channel));
	case PHIDCHCLASS_TEMPERATURESENSOR:
		return (PhidgetTemperatureSensor_create((PhidgetTemperatureSensorHandle*)channel));
	case PHIDCHCLASS_ENCODER:
		return (PhidgetEncoder_create((PhidgetEncoderHandle*)channel));
	case PHIDCHCLASS_FREQUENCYCOUNTER:
		return (PhidgetFrequencyCounter_create((PhidgetFrequencyCounterHandle*)channel));
	case PHIDCHCLASS_IR:
		return (PhidgetIR_create((PhidgetIRHandle*)channel));
	case PHIDCHCLASS_PHSENSOR:
		return (PhidgetPHSensor_create((PhidgetPHSensorHandle*)channel));
	case PHIDCHCLASS_DCMOTOR:
		return (PhidgetDCMotor_create((PhidgetDCMotorHandle*)channel));
	case PHIDCHCLASS_CURRENTINPUT:
		return (PhidgetCurrentInput_create((PhidgetCurrentInputHandle*)channel));
	case PHIDCHCLASS_STEPPER:
		return (PhidgetStepper_create((PhidgetStepperHandle*)channel));
	case PHIDCHCLASS_LCD:
		return (PhidgetLCD_create((PhidgetLCDHandle*)channel));
	case PHIDCHCLASS_DATAADAPTER:
		return (PhidgetDataAdapter_create((PhidgetDataAdapterHandle*)channel));
	case PHIDCHCLASS_CURRENTOUTPUT:
		return (PhidgetCurrentOutput_create((PhidgetCurrentOutputHandle*)channel));
	case PHIDCHCLASS_MOTORPOSITIONCONTROLLER:
		return (PhidgetMotorPositionController_create((PhidgetMotorPositionControllerHandle*)channel));
	case PHIDCHCLASS_BLDCMOTOR:
		return (PhidgetBLDCMotor_create((PhidgetBLDCMotorHandle*)channel));
	case PHIDCHCLASS_DISTANCESENSOR:
		return (PhidgetDistanceSensor_create((PhidgetDistanceSensorHandle*)channel));
	case PHIDCHCLASS_HUMIDITYSENSOR:
		return (PhidgetHumiditySensor_create((PhidgetHumiditySensorHandle*)channel));
	case PHIDCHCLASS_LIGHTSENSOR:
		return (PhidgetLightSensor_create((PhidgetLightSensorHandle*)channel));
	case PHIDCHCLASS_PRESSURESENSOR:
		return (PhidgetPressureSensor_create((PhidgetPressureSensorHandle*)channel));
	case PHIDCHCLASS_RESISTANCEINPUT:
		return (PhidgetResistanceInput_create((PhidgetResistanceInputHandle*)channel));
	case PHIDCHCLASS_POWERGUARD:
		return (PhidgetPowerGuard_create((PhidgetPowerGuardHandle*)channel));
	case PHIDCHCLASS_SOUNDSENSOR:
		return (PhidgetSoundSensor_create((PhidgetSoundSensorHandle*)channel));
	case PHIDCHCLASS_HUB:
		return (PhidgetHub_create((PhidgetHubHandle*)channel));
	case PHIDCHCLASS_GENERIC:
		return (PhidgetGeneric_create((PhidgetGenericHandle*)channel));
	case PHIDCHCLASS_MESHDONGLE:
		return (PhidgetMeshDongle_create((PhidgetMeshDongleHandle*)channel));
	case PHIDCHCLASS_FIRMWAREUPGRADE:
		return (PhidgetFirmwareUpgrade_create((PhidgetFirmwareUpgradeHandle*)channel));
	case PHIDCHCLASS_DICTIONARY:
		return (PhidgetDictionary_create((PhidgetDictionaryHandle*)channel));
	default:
		return (EPHIDGET_UNEXPECTED);
	}
}

const PhidgetChannelAttributeDef Phidget_Channel_Attribute_Def[] = {
	{ PHIDCHCLASS_VOLTAGERATIOINPUT, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_DIGITALINPUT, 0, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_DIGITALOUTPUT, 2, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_RCSERVO, 5, CHANNEL_REMOTE_SHARE | CHANNEL_REMOTE_EXCLUSIVE } ,
	{ PHIDCHCLASS_VOLTAGEOUTPUT, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_ACCELEROMETER, 4, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_VOLTAGEINPUT, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_CAPACITIVETOUCH, 3, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_RFID, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_GPS, 0, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_GYROSCOPE, 4, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_MAGNETOMETER, 3, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_SPATIAL, 6, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_TEMPERATURESENSOR, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_ENCODER, 2, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_FREQUENCYCOUNTER, 3, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_IR, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_PHSENSOR, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_DCMOTOR, 2, CHANNEL_REMOTE_SHARE | CHANNEL_REMOTE_EXCLUSIVE } ,
	{ PHIDCHCLASS_CURRENTINPUT, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_STEPPER, 4, CHANNEL_REMOTE_SHARE | CHANNEL_REMOTE_EXCLUSIVE } ,
	{ PHIDCHCLASS_LCD, 2, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_DATAADAPTER, 3, CHANNEL_REMOTE_SHARE | CHANNEL_REMOTE_EXCLUSIVE } ,
	{ PHIDCHCLASS_CURRENTOUTPUT, 0, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_MOTORPOSITIONCONTROLLER, 2, CHANNEL_REMOTE_SHARE | CHANNEL_REMOTE_EXCLUSIVE } ,
	{ PHIDCHCLASS_BLDCMOTOR, 2, CHANNEL_REMOTE_SHARE | CHANNEL_REMOTE_EXCLUSIVE } ,
	{ PHIDCHCLASS_DISTANCESENSOR, 2, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_HUMIDITYSENSOR, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_LIGHTSENSOR, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_PRESSURESENSOR, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_RESISTANCEINPUT, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_POWERGUARD, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_SOUNDSENSOR, 2, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_HUB, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_GENERIC, 1, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_MESHDONGLE, 0, CHANNEL_REMOTE_SHARE } ,
	{ PHIDCHCLASS_FIRMWAREUPGRADE, 1, CHANNEL_REMOTE_SHARE | CHANNEL_REMOTE_EXCLUSIVE } ,
	{ PHIDCHCLASS_DICTIONARY, 0, CHANNEL_REMOTE_SHARE } ,
	{ END_OF_LIST }
};
