## Simulation settings for using moveit_sim_controllers
#moveit_sim_hw_interface:
#  joint_model_group: arm
#  joint_model_group_pose: default
## Settings for ros_control_boilerplate control loop
#generic_hw_control_loop:
#  loop_hz: 300
#  cycle_time_error_threshold: 0.01
## Settings for ros_control hardware interface
#hardware_interface:
#  joints:
#    - j1
#    - j2
#    - j3
#    - j4
#    - j5
#    - j6
#  sim_control_mode: 1  # 0: position, 1: velocity
## Publish all joint states
## Creates the /joint_states topic necessary in ROS
controller_list:
  - name: /controllers/position
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
#arm_controller:
#  type: position_controllers/JointPositionController
#  joints:
#    - j1
#    - j2
#    - j3
#    - j4
#    - j5
#    - j6
#  gains:
#    j1:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    j2:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    j3:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    j4:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    j5:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#    j6:
#      p: 100
#      d: 1
#      i: 1
#      i_clamp: 1
#joint_controller:
#  type: position_controllers/JointTrajectoryController
#  joints:
#    []
#  gains:
#    {}
