# TODO: Is there any meaning to having this if it's literally just a list of points?
# A 2D Spline Line

# We define the spline by the points it passes through, as well as the start
# and end points
# To interpolate it, a full spline class, such as the `Spline` class
# in `sb_geom` should be used

# The points that the spline passes through sequentially
# (ie. the first and last points are the start and end of the spline)
Point2D[] points
